asdf-vm/asdf

- README.md
- bin/asdf
- help.txt
- lib/commands/plugin-list.sh
This command could be useful when, for example, you have a setup script and want to know if you need to install the plugin or if the plugin is already installed on the machine.
> Add a command to list the plugins already installed

- lib/commands/reshim.sh
This works most of the time, but when the directory does not contain any files `$install_path/$bin_path/*` doesn't expand (e.g. it might look like `"~/.asdf/install/lua/lua-empty-bin-dir/*"` for a Lua install). As a result what is passed to `write_shim_script` is passed a non-existent file and this causes the function to fail.  With this check, we ensure the file exists and is an executable. This ensures we are only creating shims for real executable files.
> Add check to ensure current "file" in loop is actually and executable file

- README.md
- help.txt
I wasn't aware of how the `asdf install` command worked when invoked with no arguments. Hopefully these additions will make it clear that it can install packages listed in the .tool-versions file.
> Add more details to the 'asdf install' command help and the README

- asdf.sh
- completions/_asdf
Only top level commands are supported i.e. `asdf <TAB>`
and you get a list of asdf commands. That's it.
> Adds (very) basic zsh autocompletion

- .travis.yml
- defaults
- lib/utils.sh
- test/get_asdf_config_value.bats
This closes #41 
The file should be located at `$HOME/.asdfrc` but the path can be overriden using the `ASDF_CONFIG_FILE` environment variable. If it does not exists, the defaults are used.
The default config is expected to be at `asdf_dir/defaults`, does that seem ok?
I am quite lenient on the config file format, but I think it should be ok for this use case.
I also added a few tests and a `.travis.yml` to go with, so it would be nice if you could enable travis :smiley:
> Add support for config file.

- docs/creating-plugins.md
- lib/utils.sh
Add basic support for legacy version files (e.g. .ruby-version) via an optional `get_version_from_legacy_file` script in each plugin.
Questions:
* Is it safe to equate plugin name with tool name? Or could there be variation in the tool name? (I make this assumption in the `get_tool_version_from_legacy_file` function).
* Should `get_version_from_legacy_file` be named `get-version-from-legacy-file`? It seems the other "callback" scripts use dashes. I'll be happy to change this. I only noticed this after I finished.
I have manually tested this PR with the updated asdf-ruby plugin on Ubuntu 14.04 and OSX 10.10.5.
> Add basic support for legacy version files (e.g. .ruby-version)

- lib/commands/version_commands.sh
- test/version_commands.bats
I'm not very happy about the implementation, but at least it will make `local` command consistent
with the execution behavior.
If you have any idea to make this cleaner I am all ears.
> Fix local command to support legacy files.

- bin/private/asdf-exec
- completions/asdf.fish
- lib/commands/version_commands.sh
- lib/utils.sh
I added the possibility to add fallback versions for a plugin.
As discussed in #37, this is a must for Python as (sadly) there are a lot
of scripts which work only with a single version of python, and we therefore
need to be able to call the python2 or python3 command.
A typical usage would be
```
asdf global python 3.5.1 2.7.11
pip2 install ansible
ansible # this uses python 2, but we can use it even though 3.5 is the default
python --version # 3.5.1
```
> Make it possible to use fallback versions.

- README.md
I added the Travis badge for each plugin, I'll probably send a PR to plugins which are not using Travis yet.
You can check how it looks like [here](https://github.com/tuvistavie/asdf/tree/add-travis-badges)
I also added my Python plugin to the list.
> Add travis badges to README

- asdf.sh
Related to https://github.com/asdf-vm/asdf/issues/68, an improvement for https://github.com/asdf-vm/asdf/pull/25
> Use bashcompinit instead of compinit for ZSH

- lib/commands/install.sh
- test/fixtures/dummy_plugin/bin/install
- test/fixtures/dummy_plugin/bin/list-all
- test/get_asdf_config_value.bats
- test/install_command.bats
- test/test_helpers.bash
- test/utils.bats
- test/version_commands.bats
This set and exports the `ASDF_CONCURRENCY` variable to the install script.
Each plugin should use this variable when appropriate.
I just updated my python plugin to give it a try:
https://github.com/tuvistavie/asdf-python/commit/1538892959436dd32928edba4ed5758e873fd9a2  
This closes #57
> Set ASDF_CONCURRENCY when installing

- asdf.sh
Users of `zsh` can define hook functions that execute when
the current directory changes.  If a user has their `zsh`
configured with a hook function that writes to stdout, the
`asdf` setup script will capture that output in addition to
the output of `pwd`, which causes a misconfiguration of the
`PATH` environment variable.
By redirecting the output, if any, of the `cd` command to
`/dev/null`, this ensures that the path to `bin` in `asdf`
is captured correctly regardless of `zsh` configuration.
> Fix #52: Send any `cd` output to /dev/null

- bin/private/asdf-exec
- lib/commands/install.sh
- lib/commands/list-all.sh
- lib/commands/list.sh
- lib/commands/plugin-push.sh
- lib/commands/plugin-remove.sh
- lib/commands/plugin-update.sh
- lib/commands/reshim.sh
- lib/commands/uninstall.sh
- lib/commands/version_commands.sh
- lib/commands/where.sh
- lib/commands/which.sh
- lib/utils.sh
- test/remove_command.bats
- test/utils.bats
This PR is a fix for issue #76. It takes the following approach:
1. (Redirect `display_error()` to stdout)
1. Add failing test cases for `check_if_plugin_exists()`
1. Change `check_if_plugin_exists()` to expect a plugin name instead of PATH, check if the name is empty and the directory exists -- instead of old potentially buggy behavior.
1. Update all `check_if_plugin_exists()` call sites (all tests should be green)
1. Add the failing test cases for issue #76.
1. Fix the tests by calling `check_if_plugin_exists()` in `plugin_remove_command()`
> Check if plugin exists before removing it

- README.md
- bin/asdf
- completions/asdf.bash
- completions/asdf.fish
- help.txt
- lib/commands/current.sh
- lib/utils.sh
- test/current_command.bats
- test/fixtures/dummy_plugin/bin/get-version-from-legacy-file
Renames `asdf which` to `asdf current` and adds `(set by TOOL_VERSIONS_PATH)`
This is the first step of issue #72. 
Example:
> asdf current erlang
> 17.3 (set by /Users/kim/.tool-versions)
I'm by no means a qualified shell scripter, so I would appreciate some feedback on this.
> Rename which to current

- README.md
- lib/utils.sh
I also went ahead and incremented the version number to 0.2.0. Of course we can wait to tag if there other things that need to make it into 0.2.0.
> Setup command in README should use most recent tag

- docs/creating-plugins.md
- lib/commands/current.sh
- lib/utils.sh
- test/current_command.bats
- test/fixtures/dummy_plugin/bin/list-legacy-filenames
- test/fixtures/dummy_plugin/bin/parse-legacy-file
- test/utils.bats
This implements the proposal in #81.
Now, plugins register the legacy filenames they support. ASDF searches for both legacy and .tool-version files simultaneously.
Users with plugins that only support the old legacy file api will see a warning message with instructions to update their plugin.
> Legacy File Redux

- CHANGELOG.md
- README.md
* Add everything that was merged for 0.2.0 to the changelog.
* Update install command in the readme with 0.2.0 tag.
I will tag 0.2.0 when I merge this.
Let me know there are any issues with merging this.
> Prepare for 0.2.0 release

- lib/utils.sh
- test/utils.bats
Without this patch, asdf was not able to determine the tool version
for a project located outside the user's HOME directory.
```
/work/project/
/home/me/.tool-versions
```
This changeset lets asdf find the global version stored at
$HOME/.tool-versions when the directory traversal from
the project dir was not able to find a suitable version.
> Determine version from global file when project is outside home.

- README.md
Found this plugin when looking for a way to switch MongoDB versions. Since it is not listed I decided to add it and create this PR.
A possible improvement is to split up these plugins in categories. Currently the first column reads `Language` while the list contains a few non-language plugins like Postgres, Redis, Riak and MongoDB. What do you think?
> Add MongoDB plugin to README Usage list

- README.md
This could fix #98. @HashNuke what do you think? Good solution or ugly hack?
> Ensure install commands always add asdf loading code on a new line in bashrc.

- README.md
Corrects a bug I introduced in PR #117. The -e flag enables interpretation of backslash escapes on CentOS and doesn't break OSX (OSX automatically interprets backslash escapes).
> Use -e flag when calling echo so newlines are used.

- README.md
[asdf-clojure](http://github.com/vic/asdf-clojure) is a plugin for installing [Clojure](http://clojure.org)
Closes #101
> Add asdf-clojure

- docs/creating-plugins.md
- lib/commands/reshim.sh
- test/fixtures/dummy_plugin/bin/install
- test/install_command.bats
When a shim is created, add plugin metadata so we can later know which shims belong to which plugins, this will help aid with removing unused shims on uninstall. See #67
```
```
Thanks to @duijf for the metadata proposal.
> Add metadata to shims

- docs/creating-plugins.md
This was something we talked about on #33 but never added to the plugin guide.
> Add a couple lines to the creating-plugins guide on version ordering.

- lib/commands/current.sh
- lib/utils.sh
- test/utils.bats
Before this patch, with a `.tool-versions` file like:
```
lfe ref:master
```
`get_preset_version_for` would return `ref` instead of `ref:master`.
Same was happening for `path:` versions. Actually there was PR #94 
on which I based my changes but instead of using space as delimiter
I went for using `|` which would be a lot more weird if present as
part of a file path, this also allows to specify paths which have
spaces which are much more frequent.
Closes #94 #95
> Bugfix: `ref:` and `path:` versions are not read correctly.

- lib/commands/list.sh
- lib/commands/plugin-remove.sh
- lib/commands/uninstall.sh
- lib/utils.sh
- test/list_command.bats
- test/remove_command.bats
- test/uninstall_command.bats
When the latest version of a tool is uninstalled,
Remove the plugin shims (marked with metadata at #122)
Also found lots of missing tests and added them.
Closes #67
> Shims remove on latest version uninstall (depends on #122)

- lib/commands/install.sh
- test/install_command.bats
Add a helpful error message to the install command to warn users when they don't specify a version to install. I came across this a couple days ago, and was surprised when asdf behaved as if nothing had gone wrong. Adding a simple arity check fixes this.
This fixes #132.
> Add a helpful error message to the install command

- completions/asdf.fish
Attempting to tab-complete an asdf command would result in a deprecation warning being printed.
The --authoritative/-A and --unauthoritative/-u flags have been removed from the `complete` command.
Context: https://github.com/fish-shell/fish-shell/pull/3660
> Fix fish shell's deprecation warnings when using the `complete` command

- CHANGELOG.md
- README.md
- lib/utils.sh
We've had a lot of bugfixes over the last month, so I figured it's about time to tag another patch version. I don't see anything here that would break the existing 0.2.0 API, so I think it's safe to just increment the patch version. With some of the upcoming changes there will likely be some API differences, so the next release after this one will probably be 0.3.0.
I'm going to wait until #135 is merged before merging this. Once this is merge I'll tag v0.2.1.
> Prepare for 0.2.1 release.

- lib/commands/plugin-test.sh
This is the first in a series of steps to address issue #124.
Plugins will now fail the test if the scripts in `bin/` are not executable.
> Check permissions on scripts in plugins' bin directories when testing

- README.md
[asdf-haskell](http://github.com/vic/asdf-haskell) is a plugin for installing Haskell (via stack)
> Add Haskell plugin

- lib/utils.sh
- test/version_commands.bats
When given a path: version, just check that the directory
actually exists.
Closes #95
> Allow `asdf local` and `asdf global` to take path: versions

- lib/utils.sh
- test/utils.bats
For example if asdf finds that the `ASDF_FOO_VERSION` is
defined in the current environment it will override the
version of `foo` from the `.tool-version` file.
Closes #49
> Get version from env if ASDF_${TOOL}_VERSION is defined.

- asdf.sh
Also fixed `shellcheck` warnings in the file.
Ref: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/asdf/asdf.plugin.zsh
> export ASDF_DIR so that plugins can use it to refer to the ASDF DIR

- CHANGELOG.md
- lib/utils.sh
This should fix #168. Tests were failing on my Mac due to my own custom `GREP_OPTIONS` (`--color=always`). Making this change fixed the issue.
@StevenXL you can checkout this branch if you want to make sure this actually fixes the issue you found.
> Make sure grep uses the correct settings when invoked by asdf.

- lib/commands/install.sh
When trying to use `asdf` in Alpine Linux in Docker, I got an error when trying to determine the number of CPUs, since Alpine has `sysctl` but the key `hw.ncpu` doesn't exist.
This adds an additional check for that case.
> Avoid error when sysctl is missing hw.ncpu key

- lib/commands/plugin-test.sh
Update the plugin-test command to assert that the plugin license file exists and is not empty. Fixes #161
> Update the plugin-test command to assert that the plugin license file exists

- bin/private/asdf-exec
- completions/asdf.fish
- lib/utils.sh
- test/remove_command.bats
- test/test_helpers.bash
- test/update_command.bats
- test/utils.bats
This allows asdf to pass through to the system version of a give tool if it's version is set to `system` in the `.tool-versions` file. For example `ruby system` would result in `ruby` executing the version of Ruby on the path that is not managed by asdf. Or in the case of `ruby` not being present on the path, an error.
@tuvistavie did all the work for the feature, I just added the tests for it.
This should close #55
> Support system version

- lib/utils.sh
Running "asdf current ruby" before installing any Rubies gave me:
/Users/henrik/.asdf/lib/utils.sh: line 73: [: !=: unary operator expected
No version set for ruby
> Avoid bash error when no version is set

- lib/utils.sh
Previously the version number was hard coded into `utils.sh`. This can be easy to miss when bumping version numbers elsewhere. This pull request asks git what the most recent tag in the tree is, reporting that answer instead of a static version number. The version number also contains what I suspect are
1. the number of commits since that version tag and
2. the mini-hash for the current commit.
```bash
$ asdf --version
v0.3.0-5-gbaad7dd
```
> Query git for the current version tag (Fixes #189)

- .gitignore
- README.md
- docs/creating-plugins.md
- help.txt
- lib/commands/plugin-add.sh
- lib/utils.sh
- test/plugin_commands.bats
This is my attempt at the proposal I opened: https://github.com/asdf-vm/asdf/issues/181
It's using a temporary repository under my account for now: https://github.com/doughsay/asdf-plugins.
Thoughts?  Feedback?
> Use a git repository for installing plugins.

- .gitignore
As the proposal for asdf-nodejs to [validate OpenPGP signatures](https://github.com/asdf-vm/asdf-nodejs/pull/25) has been approved and merged I guess the design is sound and other plugins can follow.
Related to: #159
> Add OpenPGP keyring support by ignoring the keyring in git

- docs/creating-plugins.md
Added one key detail about the install script (exit codes) to the plugin guide. Also suggested only populating the target directory once the installation is complete or deemed successful  to prevent incorrect asdf behavior. This is something I noticed earlier this week with the Python plugin.
> Add more details on the proper behavior of install scripts to the plugin guide

- lib/commands/current.sh
- test/current_command.bats
- test/test_helpers.bash
`asdf current` currently needs the plugin name to show the version.
With the increasing number of plugins, I think it would be nice to have
a list of all the version currently in use, so I added this functionality to
`current`. For example, here is the output I now get on my machine:
```
elixir 1.5.1 (set by /home/daniel/.tool-versions)
erlang 20.0 (set by /home/daniel/.tool-versions)
golang 1.8 (set by /home/daniel/.tool-versions)
nodejs 6.10.2 (set by /home/daniel/.tool-versions)
python 3.6.1 2.7.13 system (set by /home/daniel/.tool-versions)
ruby 2.4.1 (set by /home/daniel/.tool-versions)
```
> List all installed plugins when no argument is passed to current

- release.sh
Add a release.sh that automates the work needed to release a new version of asdf. The script ensures the version doesn't already exist and also makes sure there aren't any uncommitted changes in the working directory. The script updates the files that contain the version, then commits the changes, and then tags a new version. 
All the maintainer needs to do to release a new version is:
1.  Run the script on the master branch - `./release.sh v0.3.1`
2. Then push the branch to GitHub - `git push origin master`
This will address part of #198 
There is one TODO comment in the script. That will be addressed in another PR that will resolve the rest of #198.
> Release script

- lib/utils.sh
This helps to address (though may not completely fix) issue #202. By adding quotes around two usages of a `$file_path` variable, the utility functions support parsing a legacy or `.tools_version` file located in a path with spaces.
> Allow spaces in .tool_versions file path

- lib/commands/reshim.sh
- lib/commands/uninstall.sh
- test/install_command.bats
- test/reshim_command.bats
- test/uninstall_command.bats
This adds `asdf-plugin-version` to all generated shims.
This metadata is used to remove the shim when necessary.
I think this should handle most cases we need:
* Remove a shim when removing a version using `asdf uninstall`
* Remove a shim which has been uninstalled using the language package manager when calling `asdf reshim $PLUGIN`
Of course this will only remove a shim in the case the binary exists in no other versions of the plugin, so for example if we install a binary `dummy` using versions `1.0` and `1.1`
of a plugin, and then remove version `1.0`, the shim will
correctly stay. However, if the shim was only installed
in version `1.0` and we remove this version, the shim
will be removed.
Please take a look and let me know if I missed something.
This should fix #200
> Add asdf-plugin-version metadata to shims

- lib/commands/update.sh
`update_command` is using `git pull origin master`, when updating with `--head`,
but using `git fetch --tags` when updating to a tag, without specifying the remote.
This PR makes it use `git fetch origin --tags` instead.
This was preventing me from successfully running tests locally, as it was defaulting to another remote to which I currently don't have access.
> Use origin when updating tags

- lib/commands/install.sh
- lib/utils.sh
- test/install_command.bats
- test/utils.bats
Adds installing from a parent directory's `.tool-versions` file if found.
Fixes: #236 
I looked quickly to see if there was anything like this in the `utils.sh` but did not see anything. The `while` loops is almost a copy of the one in `find_version` but wanted to keep the addition without refactoring too much. If there is a better way to go about doing this I am open to suggestions.
> Add installing from a parent directory's .tool-versions

- lib/utils.sh
I've installed an Erlang version with `ref:` as follows:
```
$ asdf install erlang ref:OTP-20.1.2
```
Then `$ asdf list erlang` gives me the following output:
```
$ asdf list erlang
ref-OTP-20.1.2
```
Based on the output (and shell completion), I added the following line in my `.tool-versions`:
```
erlang ref-OTP-20.1.2
```
Then, although I was able to run the specified version of erlang in that machine, I cannot install the specified version using the same `.tool-versions` file in another machine.
[As written in README.md](https://github.com/asdf-vm/asdf#the-tool-versions-file), I should use `ref:` prefix, not `ref-`.
Simply replacing `ref-` with `ref:` resolved the issue.
I think all user-facing version strings should be prefixed with `ref:` instead of `ref-`; `ref-` should only be used …
> Replace `ref-` prefix in output of list command with `ref:`

- README.md
`macOS` is the new [official name](https://www.apple.com/macos/).
> Rename OS X to macOS

- lib/commands/reshim.sh
- lib/commands/version_commands.sh
- test/reshim_command.bats
- test/version_commands.bats
The MacOS version of `sed` requires you to provide a backup extension if you use the `-i` flag. Due to some weirdness in the implementation `-i'' -e` ignores the `''` and uses `-e` as the backup extension. This caused duplicate shims and `.tool-versions` files to show up with `-e` on the end of the filename.
Fixes: #242 
This problem only seems to show up if you don't provide a version to the reshim command. `asdf reshim elixir` would trigger it, but `asdf reshim elixir 1.5.2` would not. This inspired me to add a second dummy version to the reshim test, which does make it consistently fail on my machine without these fixes. However, by the time we reach the problematic sed command I don't see any difference in inputs or execution between user-provided versions or auto-discovered versions, …
> Duplicate shims

- test/banned_commands.bats
Add test that greps source code for banned commands. Currently I'm only looking for the realpath command, but there are likely many other commands we shouldn't be using if we want to ensure cross platform compatibility.
This should prevent issues like #248 from occurring in the future.
We can add to this test by adding commands to the array of banned commands defined at the top of the file.
> Add test that greps source code for banned commands.

- README.md
Updates README.md to give more detailed installation information to zsh users.
Fixes: #266
> Add zsh compinit info to readme

- asdf.sh
asdf currently adds itself to PATH even if it's already present. This fix checks whether asdf is within PATH before adding if not found.
Fixes: #261
> add to PATH once. Fixes #261

- completions/asdf.bash
- Add missing commands to completion
- Auto-completion for `plugin-add`. Only include plugins not included.
- Auto-completion for `update`
> Update Bash Completions

- lib/utils.sh
This change creates the following output when a version is set using an environment variable:
```
$ ASDF_ERLANG_VERSION=19.2 asdf current
erlang         19.2    (set by ASDF_ERLANG_VERSION environment variable)
...
```
Fixes: #292
> Specify when a version is set via environment variable

- bin/private/asdf-exec
- lib/commands/current.sh
- lib/commands/which.sh
- test/current_command.bats
These changes give additional information when no version of a plugin is currently set. Using the suggested text from `@pikeas`, it recommends the `asdf` command a user should run.
Fixes: #291
> Suggest action when no version is set

- bin/private/asdf-exec
- lib/commands/current.sh
- lib/commands/which.sh
- lib/utils.sh
- test/current_command.bats
- test/which_command.bats
This PR refactors my previous changes by drawing the "no version set" messages into a utility. It also addresses the odd output from `asdf which` that was caused by running a version check in a subshell. A new test reflects this desired behavior.
Refer: #296
Further refactoring is deserved in `which_command`. Such was likely attempted previously with the unintended consequence of hiding the version check from the user. Also, given how `check_if_version_exists` works currently, the final `else` clause of `which_command` will never run.
/cc @Stratus3D
> Refactor "no version set" messages

- test/plugin_list_all_command.bats
The `plugin-list-all` test file was not run by `bats` due to the name of the file (`.sh` instead of `.bats`). This has been fixed, and the contents of the expected output now reflect the actual output (including the repository).
> Fix `plugin-list-all` test

- README.md
- lib/utils.sh
- test/get_asdf_config_value.bats
update the README so that the `ASDF_CONFIG_FILE` environment variable is
spelled correctly
> AZDF_CONFIG_FILE -> ASDF_CONFIG_FILE typo fix

- asdf.sh
Some OSs and shells reorder items within PATH, this can result in the `asdf` entries being moved to the wrong place. This seems to occur on macOS and possibly due to the Tmux login shell option, see here for a discussion: https://github.com/thoughtbot/dotfiles/issues/587#issuecomment-369335238 .
`asdf` detects there are entries already in PATH and so does not prepend them to PATH, but due to the reordering by other tools, it stops functioning as intended.
1. Remove any `asdf` entries within PATH, regardless of their position.
2. Prepend the entries to PATH.
For PATHs without `asdf` nothing will be removed. Then the entries will be prepended.
For PATHs with `asdf` entries, they will be removed, even if in the correct position. Then the entries will be prepended.
Fixes: #288 
I noted in …
> add or move asdf to front of PATH

- asdf.sh
as per suggestion from here - https://github.com/asdf-vm/asdf/pull/303#issuecomment-371231967 :
* remove colon from `ASDF_` variables
* use `:` to normalize PATH
* match against whole `ASDF_` PATH segments
* add `:` back to string replacement - this still doesn't match against asdf segments when last in PATH
* add `:` back to asdf/PATH merging as it's no longer in the `ASDF_` vars
This fix is a stopgap to address the more serious problems (matching partial segments) raised in https://github.com/asdf-vm/asdf/pull/303#issuecomment-371231967 . I plan to address the rest of the issues is another PR with tests for each edge case.
> begin stabalising asdf prepending to PATH logic

- asdf.fish
Add a more robust check so the `$asdf_dir/{bin,shims}` directories aren't repeatedly added when launching sub shells from the current shell, or launching a program such as tmux.
Just a quick little fix. 👍
cheers 🍻
Chris
> add a more robust check for `bins` in `shims` dir for fish shell users

- bin/private/asdf-exec
- lib/commands/current.sh
- test/current_command.bats
As discussed in #305, this PR aligns exit codes for plugin not installed and plugin version not set to the one specified in the [BASH Advanced scripting guide](http://tldp.org/LDP/abs/html/exitcodes.html).
Fixes: #305 
Code `127` has been used to exit when the requested plugin version is not installed, resulting in a  "command not found" error.  
Code `126` has been used to exit when there is no version set for the requested plugin, resulting in a "Command invoked cannot execute" error.
Thank you!
> Change exit code

- lib/commands/list.sh
- test/list_command.bats
* Add feature to command `asdf list` to list all installed plugins with versions
* Add test to test the new behaviour, change the title of the existing tests
Fixes: Add ability to list all installed versions of all packages #307 
Feel free to give me feedback (specially for the bash code style)
> List command without parameter lists all installed packages with versions

- lib/utils.sh
- test/current_command.bats
- test/remove_command.bats
- test/utils.bats
- test/version_commands.bats
- test/which_command.bats
Previously, if we ran a command like `asdf install` and we encountered a
plugin that didn't exist, asdf produces an error saying "No such
plugin". Without knowing which plugin it could be referring too, we'd
have to manually go through each plugin in `.tool-versions` to find the
culprit.
With this commit, we'll now also include the plugin name as part of the
messaging for easier debugging.
Before:
```sh
$ asdf install
No such plugin
```
After:
```sh
$ asdf install
No such plugin: doesnt-work
```
> Include plugin name in error message if plugin doesn't exist

- bin/private/asdf-exec
- docs/creating-plugins.md
This feature allows a plugin to optionally change the executable path of a shim prior to execution. This is useful when the plugin tool has commands that may exist in multiple locations (like npm).
Note: This is related to fixing the `nodejs` [issue #56](https://github.com/asdf-vm/asdf-nodejs/issues/56) which prohibits upgrading the `npm` package command properly.
This is a small update to the `asdf-exec` command which checks for an optional plugin command called `exec-path` which can override the executable path to be used. In most cases this won't be necessary or would fallback to the original executable path specified in the shim file.
Fixes: https://github.com/asdf-vm/asdf-nodejs/issues/56
See sister PR in …
> Feature: Plugin Hook for Custom Executable Path

- lib/commands/plugin-add.sh
When `plugin-add` is called on a plugin that's already installed, asdf will return `0`.
```shell
$ asdf plugin-add elixir
[ clones repository, clones asdf-elixir ]
$ echo $?       # last exit code
0
$ asdf plugin-add elixir
Plugin named elixir already added
$ echo $?
0
```
Connects asdf-vm/asdf#322.
As described in asdf-vm/asdf#322, there should be different exit codes for the cases of running `asdf plugin-add <plugin>`:
case | current exit code
----------------|----------------------
new install, successful |  0
already installed | 1
failed to install | 1
To be clear: **I care about case 2** (_already installed_).
Having the same exit code (`1`) for the second and third cases makes it difficult to write scripts to install asdf in production environments (e.g. via Ansible) because running …
> Make the exit code of an already installed plugin distinct

- README.md
Can't run `asdf` in the terminal, if the shell is not restarted.
> Step for restart shell

- lib/utils.sh
Fixed #319 by forcing all dashes to underscores in the plugin name.
Shell variables don't allow dash.
> Fix for #319

- lib/utils.sh
After fixing #319 I wondered if there were any other spots where the same/similar bug existed.  I found one other location at line 126 in utils.sh.
> Fix another spot for plugin-name env var lookup

- lib/commands/list.sh
- test/list_command.bats
In order to make the output of "asdf list" a bit easier to read, this commit adds two spaces to the front of each version being written so as to indent them under the plugin.
> Fix for #330 - "asdf list" spacing

- lib/commands/version_commands.sh
- lib/utils.sh
- test/banned_commands.bats
- test/version_commands.bats
Wrote failing tests for the version-changing code for the `asdf global` and `asdf local` functions. I then wrote some code to resolve symlink paths before they make it to the code that actually edits the file, so it edits the real file instead of replacing the symlink with a real file.
Fixes: #329
> Symlink fix and tests

- asdf.fish
Currently, `asdf.fish` uses incorrect arguments for Fish's `contains` and `test` command builtins. 
This fixes the script to use valid arguments patterns.
> Fix issue with Fish shell shim loading script

- asdf.fish
- asdf.sh
- lib/commands/plugin-add.sh
- lib/commands/plugin-list-all.sh
- lib/commands/plugin-push.sh
- lib/commands/plugin-remove.sh
- lib/commands/plugin-update.sh
- lib/commands/reshim.sh
- lib/commands/update.sh
- lib/utils.sh
- test/utils.bats
This reads a custom configuration variable `install_type`, that can be set to `user` and changes the installation directory from where`asdf` installation is to `$HOME/.asdf`. 
Fixes: #275 
This fixes the problem that users experience using `asdf` with `brew`
> Install data outside asdf installation directory

- help.txt
The help text shows `<name>` and `<version>` as required options to `asdf install` when they, as a group, are optional. This pull request fixes that.
> Make help text reflect that <name> and <version> are optional in `asdf install` command

- lib/commands/reshim.sh
- test/fixtures/dummy_plugin/bin/install
- test/install_command.bats
- test/reshim_command.bats
Change reshim to generate shims only for executable files and not directories. 
Problem: When you have sub-directories inside bin path directory, it uses to create shims for the executable file and for all directories inside the path and it causes the error: "No such command in [version] of [plugin-name]"
Fixes: No open issue found with this error description.
> Fix reshim to generate shims only for executable files and not directories.

- lib/commands/current.sh
- test/current_command.bats
It seems to have been lost in 88d47bbd69dc49a601fda84c87d6380d15244daa.
Probably by accident?
I also pulled the literal bits into the format string. It looks more
readable to me that way. I'm happy to remove that if it's not desired.
> commands/current: add space before parenthesis

- lib/commands/version_commands.sh
- test/version_commands.bats
Add -p/--parent flag to `asdf local` command to tell it to crawl up the directory tree to find the nearest `.tool-versions` set the version there, rather than creating a `.tool-versions` file in the current directory if it doesn't exist.
Fixes: #65
> Add 'asdf local -p' command.

- lib/commands/plugin-test.sh
- test/plugin_test_command.bats
Fixes the error in plugin-test command caused by unset `ASDF_DATA_DIR` environment variable. Add primitive unit tests for the plugin-test command.
Fixes: #373
> plugin-test fixes

- docs/creating-plugins.md
- lib/commands/plugin-test.sh
Add --asdf-tool-version flag to plugin-test command to allow builds to pass in a specific tool version to use during the test. This is needed because not all versions of all tools are compatible with all the OSes used during the tests.
> Add --asdf-tool-version flag to plugin-test command

- docs/creating-plugins.md
Add info about using `$TRAVIS_BUILD_DIR` to test plugins on CI. So the automated tests can work with PRs and changes in another branch.
:smile:
> Add info about $TRAVIS_BUILD_DIR on the creating  plugin guide

- lib/commands/plugin-list-all.sh
- test/fixtures/dummy_plugins_repo/plugins/dummy
- test/plugin_list_all_command.bats
When checking if a plugin is installed (to display a flag) it is not
necessary to loop through all installed plugins, since we already have
a name we can check directly.
Also expand test case to test this code path too.
> Optimise listing all plugins

- help.txt
- lib/commands/where.sh
- test/where_command.bats
Allow not specifying the version on command line in which case fall back
to looking it up.
Also add tests for the `where` command.
> Make where command default to current version

- asdf.fish
- add `bin` and `shims` directories from asdf installation to PATH
- add `shims` directory from `$ASDF_DATA_DIR` (default `$HOME/.asdf`) to
PATH
- don't create directories in init script (directories are only added to
PATH if they exist, besides there is no warning when a directory does
not exist (perhaps it was a bug that was fixed))
This brings the fish snippet closer to the one for sh.
> Fix fish shell init snippet

- README.md
My first concern when reading the documentation was installation via checking out a specific release branch. The README didn't show me how to update `asdf` itself, so I held off on setting it up until I knew that in the future I wouldn't have an outdated version that was annoying to update via git.
I'm guessing some others may have similar concerns as well, so I thought it would help (and shouldn't hurt) to add a short section to the README.
> Add README documentation on updating asdf

- README.md
While updating the README in #397, I noticed that the link text for Daniel Perez did not match the href, so I fixed it as well.
_Would you prefer one commit with a number of tweaks to the README, or accept/reject each on it's own?_
> Fix README typo of maintainer Daniel Perez's username

- README.md
While I was making a couple of other minor changes to the README, I noticed that large sections were wrapped to 80 characters and other sections were not. In case your desire as maintainers is to have the Markdown source, I've wrapped it everywhere except in long code samples and URLs.
I also made a couple minor content tweaks.
> Wrap README to 80 characters where possible; minor rewording

- lib/commands/current.sh
- test/current_command.bats
`asdf current` failed when a plugin had multiple versions set (e.g. `asdf global python 3.6.6 2.7.12`).
This fixes the issue.
> Fix current behavior when multiple versions of a plugin are set

- lib/commands/install.sh
- test/install_command.bats
````
echo "nodejs 8.12.0" > .tool-versions
echo -n "nodejs 8.12.0" > .tool-versions
````
I'm really not sure how we ended up with a .tool-versions file without a trailing newline, but it caused a significant amount of confusion. :)
Implementation for fix borrowed from https://unix.stackexchange.com/questions/418060/read-a-line-oriented-file-which-may-not-end-with-a-newline. I'm hoping the existing test coverage will prevent a regression.
Thanks for asdf-vm; it rocks!
> support .tool-versions content even if it does not end in a newline

- lib/utils.sh
Use `ASDF_DATA_DIR` in `get_executable_path` function if it is set. Otherwise fall back to `$HOME/.asdf`.
Fixes: #402
> Make get_executable_path use `ASDF_DATA_DIR`

- completions/asdf.bash
- completions/asdf.fish
Currently, when a message is printed to `stderr` during tab completion, it appears inline, causing an awkward user experience. This is easily reproducible by trying to tab complete with a fresh clone of `asdf` (no plugins installed):
The fix redirects all `stderr` to `/dev/null` during tab completion, so if there is an error when trying to suggest completions, `asdf` will simply suggest nothing rather than report out a message.
I think this is the most user-friendly approach, but we could also remove the "Oohes nooes" message from `plugin-list` to silence an expected error, while still reporting unexpected errors during tab completion, such as:
```
asdf install golang <TAB> /root/.asdf/plugins/golang/bin/list-all: line 34: curl: command not found
```
> Silence errors during tab completion

- lib/commands/update.sh
- test/update_command.bats
`asdf update` should be using `ASDF_DIR`, the directory of the git repo, rather than `ASDF_DATA_DIR`, the location of various data.
The following changes are included as a result of this fix:
- `cd` into `${ASDF_DIR}` instead of `$(asdf_data_dir)` before performing an update
- Make sure that the directory is part of a `git` repo before performing an update. This gives a better error message, and works for homebrew installations as well
- Add a test case for the above behavior
- Fix test setup to work for certain `asdf` installations. Details below
I have a somewhat unique setup in that I have `asdf` installed as a git submodule in my dotfiles, but I keep the `ASDF_DATA_DIR` separately as the default of `$HOME/.asdf`. The `update_command` tests were failing for me unrelated to this change …
> Fix issues with update command

- asdf.sh
Only one shims directory needs to be added to `PATH`.
Related to #406
> Remove unused asdf shims directory

- lib/commands/current.sh
- lib/utils.sh
Travis.CI build was failing on OSX.
> Fix shellcheck warnings on OSX

- lib/commands/list.sh
- test/list_command.bats
Previous implementation exits abruptly when no version is installed for
a plugin. This prevented the list command from listing the versions for
some other plugins.
This commit allows list command to continue executing even when no
version is installed for some plugins.
Example, plugin a with 1.0, b with none, and c with 2.0.
Previous implementation:
```
$ asdf list
a
1.0
b
No versions installed
```
After commit changes:
```
$ asdf list
a
1.0
b
No versions installed
c
2.0
```
> Continue list even when version is not found

- asdf.fish
This sets `fish_user_path` instead of `PATH`. This is the proper way to load custom paths in fish. Prior to this change the asdf shim path was being appended to the default path for newer versions of fish, resulting in asdf using system executables. I've only confirmed the bug in the fish 3.0, but I suspect it didn't exist prior to 3.0.
Fixes: https://github.com/asdf-vm/asdf/issues/420
This fix will not work for versions of fish prior to 2.1. This latest 2.1 version was published in Feb 2015.
> Fixed user paths for fish

- README.md
- docs/core-manage-asdf-vm.md
Update README link to uninstall instructions of the new `docs/`
Fixes: this comment - https://github.com/asdf-vm/asdf/commit/2fcde332ae5a0026d4ff40cb0713216e53111170#commitcomment-31950054
> Readme uninstall fix

- CHANGELOG.md
- bin/private/asdf-exec
- bin/private/asdf-tool-exec
- lib/commands/reshim.sh
- lib/utils.sh
- test/install_command.bats
- test/reshim_command.bats
- test/shim_exec.bats
- test/uninstall_command.bats
- test/utils.bats
Features
* New shim version meta-data allows shims to not depend on a particular plugin
nor on its relative executable path (#431)
Upgrading requires shim re-generation and should happen automatically
by `asdf-exec`:
`rm -rf ~/.asdf/shims/` followed by `asdf reshim`
* Added lots of tests for shim execution.
We now make sure that shim execution obeys plugins hooks like
`list-bin-paths` and `exec-path`.
* Shim exec is now performed by a new `bin/private/asdf-tool-exec` that might
be faster for most common use case: (versions on local .tool-versions file)
but fallbacks to slower `get_preset_version_for` which takes legacy formats
into account.
* Shim exec recommends which plugins or versions to set when command is
not found.
Fixed Bugs
* Allow many plugins to provide shims with same …
> New shim metadata to allow many plugins with same executable names

- CHANGELOG.md
- bin/asdf
- bin/private/asdf-exec
- bin/private/asdf-tool-exec
- help.txt
- lib/commands/reshim.sh
- lib/commands/shim_versions.sh
- lib/utils.sh
- test/install_command.bats
- test/reshim_command.bats
- test/shim_exec.bats
- test/shim_versions_command.bats
- test/uninstall_command.bats
- test/utils.bats
Add `asdf shim-versions command` (#380)
For example `asdf shim-versions npm` will list the plugins and their
versions on which the `npm` command is available.
[Based on changes](https://github.com/vic/asdf/compare/new-shim-meta..shim-versions-command) from #432
> List on which plugins and versions is a shim available

- CHANGELOG.md
- bin/private/asdf-exec
- bin/private/asdf-tool-exec
- lib/commands/install.sh
- lib/commands/reshim.sh
- lib/commands/uninstall.sh
- lib/utils.sh
- test/install_command.bats
- test/reshim_command.bats
- test/shim_exec.bats
- test/uninstall_command.bats
- test/utils.bats
Suppose a `foo` plugin is installed and provides a `bar` executable.
The following hooks will be executed when set in `.asdfrc`:
```shell
pre_asdf_install_foo = echo will install foo version ${1}
post_asdf_install_foo = echo installed foo version ${1}
pre_asdf_reshim_foo = echo will reshim foo version ${1}
post_asdf_reshim_foo = echo reshimmed foo version ${1}
pre_foo_bar = echo about to execute command bar from foo with args: ${@}
post_foo_bar = echo just executed command bar from foo with args: ${@}
```
[Based on changes](https://github.com/vic/asdf/compare/new-shim-meta..command-hooks) from #432
> user configurable pre-post command hooks

- CHANGELOG.md
- bin/asdf
- help.txt
- lib/commands/shim-env.sh
- test/shim_env_command.bats
New `asdf env <command>` can be used to print or execute with the env that would be used to execute a shim.
> Add `asdf env` command

- docs/core-manage-asdf-vm.md
Hi. Just a quick 'n easy doc improvement :+1.
_Note: I still use asdf, just needed a way to temporarily disable a global version and stumble upon #238 which mentioned ~/.tool-versions and this piece of documentation. Actually it could be nice adding a `global-unset` command or something :question:_
> Mention ~/.tool-versions in uninstalling instructions

- asdf.fish
Export `ASDF_DIR` variable for fish shell, so `asdf update` works properly no matter the current folder.
Fixes: https://github.com/asdf-vm/asdf/issues/436
> fix "asdf update" on fish

- docs/core-manage-asdf-vm.md
This PR adds OS specific commands to install needed plugins for macOS and Fedora. Previously it was a list of plugins to install.
Fixes: #453
> Add commands for macOS and Fedora plugins section docs

- README.md
An attempt to clarify the purpose of asdf by making it clear it's for managing multiple versions of runtimes. I'm not sure if this makes it more understandable or not. I just noticed we didn't say much about versions. What do you think @jthegedus ?
> Add the word `version` to README tagline and description

- docs/core-manage-asdf-vm.md
This PR adds documentation to cover that components can be installed via [Spack](https://spack.io/) on macOS. There's really no difference in the package names (and so on), but this serves to show that there are more options than just Homebrew! 
As a side note, I do not know if the website is automatically generated from GitHub. If so, it might be good to wait on this PR for a little while. I recently had the final specification for `libyaml` merged into Spack - I'm not entirely sure when that becomes more broadly available.
> Add a note about Spack installation

- docs/core-configuration.md
- docs/core-manage-versions.md
- lib/utils.sh
- test/shim_exec.bats
- test/which_command.bats
Some regressions had been introduced in version handling, the most important one being the support for legacy files.
Support for multiple versions of the same plugin had also changed, making it incompatible with `asdf current`, `asdf local` and `asdf global` commands.
Up to 9b27848d07b86a7fe5c5294e89bf7f3674ea50f2, multiple versions could be set in `.tool-versions` by separating versions with a space. After 9b27848d07b86a7fe5c5294e89bf7f3674ea50f2, the same could be achieved by adding multiple lines with the same plugin name.
However, this plays badly with `asdf local` and `asdf global` as there is no easy way to set multiple versions, while it is trivial with the single line approach.
This PR reverts the behavior to use space separated versions.
I also added a regression test for legacy …
> Fix version handling

- asdf.fish
fish_user_paths variable is prepended to $PATH automatically. Some people set fish_user_paths, while others set PATH.
It will be better to test if fish_user_paths is set, and prepend it if it is, while just prepending to PATH otherwise.
[setting $PATH in fish shell](http://fishshell.com/docs/current/tutorial.html#tut_path)
> Update fish_user_paths only if it is defined

- asdf.sh
The mksh shell (and perhaps others too) will not be able to determine a
sourced script's path by looking at either `${BASH_SOURCE[0]}` or `$0`.
By capturing the value of `$_` as the very first thing the script does,
`asdf.sh` can use that as the input for `dirname` in order to determine
a value to use for `$ASDF_DIR`.
I have tested this change with mksh to confirm that it works, and have
also tested it with both bash and zsh to verify that neither of those
stop working.
This resolves the only compatibility issue I've ran into with asdf,
caused by mksh sourcing a script. All subsequent asdf usage involves an
asdf executable doing the sourcing, so it's bash to bash at that point.
> asdf.sh: support mksh

- lib/utils.sh
- test/shim_exec.bats
With the previous version, the following case would fail.
It would use python 2.7.15 when running pip
instead of version 3.7.2.
Shim for `pip`
```bash
exec /home/daniel/.asdf/bin/asdf exec "pip" "$@"
```
`.tool-versions`:
```
python 3.7.2 2.7.15 system
```
> Fix select version when multiple versions available

- asdf.fish
- asdf.sh
- bin/asdf
- completions/asdf.bash
- completions/asdf.fish
- lib/commands/version_commands.sh
- test/version_commands.bats
Add a "shell" command similar to the existing "global" and "local" commands, which sets the version in an environment variable instead of writing it to a file. This was inspired by the similar functionality in rbenv.
It works by adding a wrapper function for the asdf command. This forwards to a "sh-shell" command that returns the exports as shell code which is then evaled by the wrapper. This is a little gross, but we need to run the code in the shell context in order to set variables, and it matches rbenv's approach.
Fixes: #378
> Add "shell" subcommand for setting versions in shell session

- docs/homepage.md
The homepage wasn't importing the required `.md` files appropriately due to the Docsify embed feature requiring single quotes, not double quotes.
We should update the information about Prettier use to specify that these pages require single quotes.
> fix quote bug in root page

- lib/commands/where.sh
- test/where_command.bats
Update `where` command so `System version is selected` is printed instead of `Version not installed` when the system version is selected for the plugin.
Fixes: #477
> Improve output of where command when system version is set

- lib/utils.sh
- test/banned_commands.bats
`grep -y` seems to be available only on some implementations on `grep` and was not needed here.
This should fix #488
> Fix shim_plugin_version

- docs/index.html
- docs/scripts/docsify-edit-on-github.js
This should fix #469 
Edit on github plugin is trivial so I think we're better off hosting our customized version than trying to get this merged upstream.
> Use custom edit on github plugin. Fix #469

- docs/core-manage-asdf-vm.md
Added installation, shell setup, and upgrade instructions for use with Homebrew.
Added a brief item for uninstall related to package managers.
Fixes: #425
I decided to not make the `Add to your Shell` portion a tab item of its own, instead keeping it under `Bash on macOS`. I followed nomenclature found elsewhere in the document to clarify variant install situations.
It's worth noting that Homebrew can be used with Windows 10 with Windows Subsystem for Linux, though I'm not sure if that is applicable to `asdf` at present.
> Add Homebrew instructions

- lib/commands/install.sh
- lib/utils.sh
- test/install_command.bats
- test/utils.bats
Make install command ignore comments. Skip lines matching the pattern `^#.*`, e.g. any line starting with `#`.
Fixes: #489
> Make install command ignore comments

- CHANGELOG.md
- lib/commands/shim-exec.sh
- lib/utils.sh
- test/shim_exec.bats
As discussed, this reverts to the previous behavior of executing shims with `exec`.
This is a step back towards #409 but I do not think we have a way around it.
Fixes #475
> Revert to using exec when running a shim

- lib/utils.sh
- test/current_command.bats
#498 did not support comments when using `asdf current`.
This should fix the issue.
> Fix current when .tool-versions contains comments

- docs/core-manage-asdf-vm.md
I was doing a test of getting up and running using asdf on a fresh Ubuntu install it became aparant that curl and unzip were required for some plugins to install, it makes sense to me to add these to the base dependencies list to give a better getting started experience.
> Add more plugin dependencies 

- lib/commands/reshim.sh
- lib/utils.sh
- test/reshim_command.bats
The current behavior in shims is to check if there's an existing shim for
which the shim we're currently checking is a prefix. For example, if the shim
has
Then adding a shim for `erlang 21.2` will fail.
This updates the `grep` check to match the end of the line as well so we
always get a full version check.
Fixes #517
> fix: check shims for the full version

- lib/utils.sh
Address shellcheck warning. Use shell globbing instead of iterating on the output of `ls`.
Fixes: #513
> Address shellcheck warning and use shell globbing instead of ls

- lib/commands/install.sh
- test/install_command.bats
I set out with the goal to make `asdf install` install plugin versions from legacy version files (like `.nvmrc`).
However, since `asdf install` normally loops through the `.tool-versions` file, and wouldn't do anything at all if the `.tool-versions` file doesn't exist, I had to change the general approach to determining what to install.
So now, instead of looping through the `.tool-versions` file, **the command will loop through all available plugins, and ensure that whatever version is selected for the plugin and in whichever way, this version is installed.**
(One downside is it might try to install tools irrelevant to my current project - for example: if I have the elixir plugin, and the nodejs plugin, and I'm only using the latter in my current project, but I don't have the globally …
> Change `asdf install` to loop through available plugins and check legacy version files

- docs/core-manage-asdf-vm.md
Adds instructions for adding asdf to your shell when using zsh and Homebrew.
This was mostly copied from https://github.com/asdf-vm/asdf/pull/496
I believe similar instructions should also be added for fish but I don't use it and cannot test it at the moment.
> Add Homebrew instructions for ZSH

- docs/core-manage-asdf-vm.md
Adds instructions for configuring asdf in fish shell using Homebrew.
Fixes #545 
Based on #537
> Add Homebrew instructions for fish shell

- docs/core-manage-asdf-vm.md
The recommended Homebrew setup required running two `brew --prefix` commands
to the shell profile. `brew` commands can be slow, so this introduced a notable
lag when sourcing the shell profile.
Homebrew paths do not change, so we can determine the necessary paths one time
during setup and use static paths in the shell profile.
Also changes one `` ```bash`` to `` ```shell`` in the ZSH documentation, to match the rest of the ZSH documentation.
> Docs: Homebrew setup: do not add brew commands to the shell profile

- lib/commands/plugin-test.sh
This makes 2 changes:
1. Provides an alternative way for `asdf plugin-test` to set up its environment, by copying the contents of $ASDF_DIR to $TEST_DIR instead of doing a git clone. This fixes `plugin-test` for homebrew installations
2. Makes a small logic fix to silence a warning when GITHUB_API_TOKEN or OAUTH_TOKEN are present, but not both (before both needed to be set before the warning would disappear, which seems incorrect).
Fixes: #509
This may be an inadequate solution if someone installs asdf such that $ASDF_DIR is equal to $ASDF_DATA_DIR, since all installed plugins and packages will also be copied which could be wasteful of time and resources. I don't know if that's typical or not of a pure git installation as I haven't done that myself, though.
> Fix for asdf plugin-test when installed with brew, and a minor logic fix to a warning

- lib/utils.sh
- test/shim_env_command.bats
Correct logic that constructs path for callback in the `with_plugin_env` function.
Fixes: https://github.com/asdf-vm/asdf/issues/543
> with_plugin_env PATH fix

- asdf.fish
Rather than doing string munging to identify if a directory is in the path already, use the fish builtin `contains`.
Fixes: #550 
I'm by no means a fish expert. I'm using this patch locally to fix #550 and it's working, but I can't guarantee it works across all versions of fish, for example.
Just as a reference for people not familiar with fish shell:
* [`contains`](https://fishshell.com/docs/current/commands.html#contains) function
* [Example](https://fishshell.com/docs/current/tutorial.html#tut_conditionals) of boolean logic (`if expr;  and expr`).
> Fix PATH spacing issue in asdf.fish

- lib/commands/version_commands.sh
- test/version_commands.bats
Issue #378 proposes the `shell` subcommand and PR #480 implements it.
But #378 also mentions about its `--unset` option to unset ASDF_WHATEVER_VERSION variable which is missing from PR #480.
This PR adds support of `--unset`.
before
```shell
$ asdf current ruby
2.7.0-dev (set by /Users/sakuro/.tool-versions)
$ asdf shell ruby 2.6.3
$ asdf current ruby
2.6.3    (set by ASDF_RUBY_VERSION environment variable)
$ asdf shell ruby --unset
version --unset is not installed for ruby
```
after
```shell
$ asdf shell ruby
Usage: asdf shell <name> <version> | --unset
$ asdf current ruby
2.7.0-dev (set by /Users/sakuro/.tool-versions)
$ asdf shell ruby 2.6.3
$ asdf current ruby
2.6.3    (set by ASDF_RUBY_VERSION environment variable)
$ asdf shell ruby --unset
$ asdf current ruby
2.7.0-dev (set by …
```
> Add --unset option to shell subcommand

- lib/commands/current.sh
- lib/commands/install.sh
- lib/commands/where.sh
- lib/utils.sh
- test/install_command.bats
- test/utils.bats
The install code did not take into account the possibility of multiple tool versions specified in a single `.tool-versions` file separated by whitespace.
Fixes: #540
I decided to rename the `find_version` function to `find_versions`, since it can return multiple space-delimited versions. If anyone feels this change is unnecessary I'll be happy to revert it.
> Fix multiple version install

- lib/utils.sh
- test/utils.bats
Handle executable names with dashes as regular strings. Write unit test to ensure the `with_shim_executable` handles shims like this properly.
Fixes: #565
> Handle dashes in executable names properly

- lib/commands/version_commands.sh
This sed command was using `/` as the delimiter for the find and replace command. This caused problems when the variable used in the expression also contained `/`, such as when a path was specified. See #559 for more details.
I was unable to write a unit tests for this, as the problem only manifests in an error when the path starts with `/U`, and I didn't want the unit tests trying to create a directory in root.
Fixes #559
> Fix sed command so it handles paths correctly

- appveyor.yml
This adds support for windows through Appveyor CI.
Closes https://github.com/asdf-vm/asdf/issues/450
> appveyor.yml: Add support for Windows

- completions/asdf.fish
Fixes issue with suggestions when running `fish` on OSX.
OSX `sed` is not GNU `sed`, and doesn't support the `\s` whitespace character sequence. This results in autocompletion suggestions including leading spaces, e.g.,
```
$ asdf local python \ \ 3.8.0
```
Using the POSIX compliant `[[:space:]]` sequence is more compatible, and removes the unnecessary spaces on OSX.
> Fix completion suggestions for OSX / fish

- CHANGELOG.md
- bin/asdf
- completions/asdf.fish
- docs/core-commands.md
- docs/core-manage-versions.md
- lib/commands/install.sh
- lib/commands/latest.sh
- lib/commands/list-all.sh
- test/install_command.bats
- test/latest_command.bats
- test/list_command.bats
This PR integrates the logic from [xxenv-latest](https://github.com/momo-lab/xxenv-latest) to install the latest stable version of a tool. It adds a `latest` command to show the latest version:
- `asdf latest python` prints `3.7.4`
- `asdf latest python 3.6` prints `3.6.9`
This gets used by `asdf install` to install the latest version:
- `asdf install python latest` installs Python 3.7.4
- `asdf install python latest:3.6` installs Python 3.6.9
It also adds the ability to filter versions returned by `asdf list-all` by accepting an additional version substring:
- `asdf list-all python 3.7` only lists Python 3.7 versions
Fixes: #216 
I need to add unit tests. Any suggestions are welcomed.
> Add support for installing the latest stable version of a tool

- CHANGELOG.md
- bin/asdf
- docs/plugins-create.md
- test/plugin_extension_command.bats
When a plugin provides custom executables or bash-scripts under its `bin/` directory,
it's now possible to invoke them with:
```shell
asdf nodejs import-release-team-keyring
~/.asdf/plugins/nodejs/bin/import-release-team-keyring
```
As in nodejs case, plugin authors can use this feature to provide utilities,
or people can create plugins that are just extensions to asdf itself.
See `docs/plugins-create.md` for more info.
Kudos to @imbsky for the idea.
> New feature: asdf extension commands

- lib/utils.sh
In some Linux distributions it is possible to run hooks after upgrading the system. These hooks, in the case of [pacman](https://wiki.archlinux.org/index.php/pacman), which is the package manager for [Arch Linux](https://www.archlinux.org/), are run as root. 
With that in mind, when plugins are updated, several calls to the ```asdf_data_dir()``` are processed, returning a path containing ```$HOME``` environment variable, which is incorrect since the current user executing the update is different from the one who installed ```asdf``` in the home directory. 
Also at this point ```$ASDF_DATA_DIR``` is empty (for some reason has not been set). 
This fix reuses the existing method: ```asdf_dir()``` in order to retrieve the correct path where the plugins are installed. 
Fixes: #582
For some …
> asdf_data_dir() returning incorrect path when running as root.

- CHANGELOG.md
- lib/utils.sh
This will help people running on asdf master be able to report
issues and maintainers can know the precise git commit where the
error was reported.
For example, on #598 it would be better to know the exact version being used.
> `asdf --version` shows git-revision when asdf_dir is a git clone.

- lib/asdf.sh
- test/banned_commands.bats
`command eval` does not work in ZSH
Replace `command eval` with just `eval`
> Fix shell compatibility with ZSH

- docs/core-manage-plugins.md
This PR fixes the syntax for `plugin-*` commands in the docs.
I'm not a regular contributor to the codebase so it's possible this isn't correct, but it does match the usage as recommended by `asdf help` on the latest version.
> docs: update plugin-* usage

- docs/core-manage-asdf-vm.md
MacOS now ships with Zsh as the default shell. I added a note for this in the Mac installation area of the docs.
> Update installation for Zsh on macOS Catalina

- lib/utils.sh
- test/shim_exec.bats
Often time when working on multiple projects and multiple versions, the version that specified in `.tool-versions` or legacy config like `.ruby-version` is not yet installed in the system. When that happens this is what we see
So instead of telling us what version is missing, asdf tell us to change the configuration into one that has been installed in our system.
This PR changes the warning by giving us information about which version is missing, and option to install the missing version or replace existing project to use different version that is available.
> Clarify instructions when <version> of a <shim_name> is missing.

- lib/utils.sh
- test/shim_exec.bats
In #609 a clearer error message was added when you're trying to run a shimmed command, but you don't have a correct version. This PR fixes an issue where that code was assuming that the shim and plugin share a name.
An example of where this is not the case is the "nodejs" plugin, as the shim is installed as "node"
In other areas of the utils file, it works on the basis that there may be multiple plugins that provide for that shim, so I have worked on the same basis
> Fix issue with preset version warning assuming that the shim name and plugin name are the same

- completions/asdf.bash
`$ asdf plugin-add <TAB>` currently yields this mess:
Fixing it to provide a clean list of available but not installed plugins (this is also what fish completion already does and somehow got overlooked in bash version):
> Fix bash completion for `plugin-add`

- test/update_command.bats
Don't allow the `rm` command to hang waiting for user input to confirm the deletion of the `.git` files. `rm` was causing the test to hang.
Fixes: #634
> Fix hanging 'asdf update is a noop for non-git repos' test

- lib/commands/command-export-shell-version
- test/version_commands.bats
`unset` does not exists on fish so `asdf shell xx --unset` was failing. This fixes the issue.
> Fix asdf shell xx --unset for fish

- lib/utils.sh
- test/test_helpers.bash
- test/utils.bats
Unset `ASDF_DIR` before running tests to ensure tests always pass regardless of whether the user already has `ASDF_DIR` set in their shell.
Fixes: #634
> Misc. Test Improvements

- lib/utils.sh
If ASDF_DATA_DIR variable is undefined it will assign an empty value to
it so bash instances running with set -o nounset can run the script
without error.
> Defaults to empty ASDF_DATA_DIR

- docs/core-manage-plugins.md
Fixes: updates example url to avoid redirect users to deprecated repository.
https://github.com/skotchpine/asdf-java isn't been maintained anymore.
> [docs] clean up: update example with maintained project url

- asdf.sh
This avoids borking when a user has `set -u` (a.k.a. the `nounset` option) enabled.
Fixes #655.
> Default ZSH_VERSION to empty string.

- lib/utils.sh
- test/get_asdf_config_value.bats
- test/which_command.bats
Previously, the shims directory was only excluded for system versions, which meant that `asdf exec` would fall back to a shim if the install didn't have the desired binary. If the shims are up to date this isn't a problem since we check the metadata, but if those were out of sync the command would just infinitely recurse.
I'm not sure what the reason was for the current setup, but I looked through the uses of the function and I'm not seeing anywhere it is required.
Fixes: No issue
I also made a small tweak to the config test to make it pass, it was picking up my user `.asdfrc`.
> Ignore shim directory for executable lookups

- lib/commands/version_commands.sh
All other instances of `check_if_plugin_exists` pass the value as `plugin_name`. Minor fix for consistency.
> fix: consistent use of plugin_name

- docs/core-manage-plugins.md
- docs/plugins-create.md
Replace references to aliases in the form of `command-subcommand` with `command subcommand`
Resolves #645
> Update examples using subcommands

- lib/utils.bash
In strict mode bash this needs to be changed to avoid throwing an error.
> Default to empty version to avoid error on strict mode bash

- README.md
Change the incorrect/confusing bullet point under the "Why use asdf-vm?" heading in the readme.
Fixes: #529
> Change bullet point under "Why use asdf-vm?" heading

- lib/commands/command-update.bash
- test/update_command.bats
If asdf-vm was installed with a package manager and the user doesn't have the necessary permissions to update it with `asdf update`, asdf-vm emits an informational message and exits with exit code 1.
This makes it hard to programmatically detect whether the update failed or wasn't even attempted because it's not possible.
With this change, asdf-vm would exit with the exit code 2 if updates are disabled instead of exit code 1, which signals an error during update.
Refs r-darwish/topgrade#367
> Use different exit code if updates are disabled

- asdf.sh
- docs/core-manage-asdf-vm.md
#544 released in https://github.com/asdf-vm/asdf/releases/tag/v0.7.7 changed:
```diff
- if [ -n "$ZSH_VERSION" ]; then
-   autoload -U bashcompinit	
-   bashcompinit
+ if [ -n "${ZSH_VERSION:-}" ]; then
+   fpath=(${ASDF_DIR}/completions $fpath)
+   autoload -Uz compinit
+   compinit
+ fi
```
which results in `compinit` being executed multiple times (should people use a framework or explicitly use compinit in their own `zshrc``). `compinit` is designed to be called once, so we should not automatically run it here and double up on those already calling it.
This has performance implications and concerns were raised about asdf being **unexpectedly** intrusive.
Clearer documentation updates will rectify any issues with this removal. I would wager few ZSH users are relying on asdf to run …
> fix: remove automatic compinit

- .github/workflows/workflow.yml
- CHANGELOG.md
- docs/plugins-create.md
- lib/commands/command-plugin-add.bash
- lib/commands/command-plugin-remove.bash
- test/fixtures/dummy_plugin/bin/plugin-add
- test/fixtures/dummy_plugin/bin/plugin-remove
- test/plugin_add_command.bats
- test/remove_command.bats
- test/test_helpers.bash
* Add support for custom `plugin-add` and `plugin-remove` in plugins
* Add configurable command hooks for plugin installation and removal
```shell
pre_asdf_plugin_remove = echo will remove plugin ${1}
pre_asdf_plugin_remove_foo = echo will remove plugin foo
post_asdf_plugin_remove = echo removed plugin ${1}
post_asdf_plugin_remove_foo = echo removed plugin foo
```
Closes #670
> Support customizing plugin-add and plugin-remove

- lib/commands/command-plugin-add.bash
Changed exit code to 0 and message output to stdout when trying to add an already added plugin
Fixes: #659
> Change exit code to 0 and output message to stdout

- .github/ISSUE_TEMPLATE/config.yml
Removing the option for users to not choose one of our predefined issue templates when they click "New Issue". This is needed now that we have multiple issue templates (#694).
> Force users to use one of our predefined issue templates

- CODEOWNERS
Add a basic CODEOWNERS file with a rule that specifies the core team as the owner of all the files in this repository.
> Add basic CODEOWNERS file

- docs/core-manage-asdf-vm.md
Only list packages needed by asdf core in the asdf documentation.
I searched the codebase for the commands provided by all these packages and removed the ones that were not used at all.
Fixes: #511
> Change plugin dependencies section to asdf dependencies

- docs/core-manage-asdf-vm.md
The previous instructions did not work on modern Fish (3.1.0) and lead to the following error:
> source: Error encountered while sourcing file '(brew --prefix asdf)/asdf.fish':
> source: No such file or directory
> Documentation: Fix Fish source syntax

- docs/core-commands.md
> Fix a typo in the env command documentation

- docs/core-manage-versions.md
> Fix typo in docs/core-manage-versions.md

- docs/plugins-create.md
Hi, I tried creating a plugin for asdf-vm. I found a dead link in the documentation and fixed it.
The reason is that [the commit changed the file extension](https://github.com/asdf-vm/asdf/commit/52cbf1165c79c7efbb1c9b2f26167a047a7335d0).
I also think there is a way to change the link to the master branch.However, that selection line number is unstable. e.g) https://github.com/asdf-vm/asdf/blob/master/lib/utils.bash#L98
This P-R keeps a commit hash to stabilize the line number. What do you think?
My plugin was easy to create. Thanks to the maintainers of the documentation.
> Fix dead link by changing the extension to sh

- lib/commands/command-latest.bash
`sort`'s `--version-sort` flag isn't available on all OSs as reported in the linked issue and the reason for a custom `sort_versions` function in `command-update.bash` https://github.com/asdf-vm/asdf/blob/8a5c70b2dd43f918c51548a52c150c3c9ff4a547/lib/commands/command-update.bash#L46
Since the `asdf list-all "$plugin_name"` part of the command returns a sorted list, we do not need to perform any sort here. We should be able to safely remove it.
Fixes: #698 
I originally replaced this sort with the aforementioned custom sort_versions function and it seems that it is not idempotent. Something of note since we recommend this function for plugin authors.
> fix: remove sort --version-sort from command-latest as list is already sorted

- docs/core-manage-asdf-vm.md
Communicate that asdf relies upon plugins and how the Doc site menus correspond to each step of that process.
Fixes: #708 
I also moved the "Dependencies" section to the top of the `asdf` install section
> docs: improve introduction and lift dependencies higher

- docs/core-commands.md
- docs/core-manage-asdf-vm.md
- help.txt
The help text and "All Commands" doc site page have been getting updates differently. They've fallen out of sync. While crude, I would like to solve the discrepancy by directly importing the `help.txt` file into the docs.
I don't imagine that page to be heavily visited, it was only included for completeness of the documentation site. This is a better in-between.  
I removed the 2 space indentation of the `help.txt` for all commands. This allows for more content to be horizontally filled.
I removed the inline word wrapping. I will follow this PR up with a change to render the help text via `awk` on `asdf`/`asdf help` and perform wrapping.
> docs: synchronize help text

- lib/commands/command-plugin-list-all.bash
- lib/commands/command-plugin-list.bash
- test/plugin_list_all_command.bats
- asdf plugin list
- asdf plugin list all
Avoid hard dependency on `column` command. This command
is not included in a fresh ubuntu container and not
defined in posix:
https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html
Also makes the output of `asdf plugin list all` line-streamed
on the second column value
> fix: remove `column` command in favor of awk

- .github/workflows/workflow.yml
- bin/asdf
- completions/asdf.bash
- lib/asdf.sh
- lib/commands/command-export-shell-version.bash
- lib/commands/command-install.bash
- lib/commands/command-local.bash
- lib/commands/command-plugin-list.bash
- lib/commands/command-plugin-test.bash
- lib/utils.bash
Remove `shfmt` flags and rely solely on standard EditorConfig settings being inferred by `shfmt`. This requires dropping switchcase indenting (`shfmt -ci`).
`shfmt` is currently being used to perform format checking in our GitHub Actions.
`shfmt` supports using `editorconfig` files, but not when "Parser or Printer options" are set.
<details>
<summary>shfmt --help</summary>
```
➜ shfmt --help
usage: shfmt [flags] [path ...]
If the only argument is a dash ('-') or no arguments are given, standard input
will be used. If a given path is a directory, it will be recursively searched
for shell files - both by filename extension and by shebang.
-version  show version and exit
-l        list files whose formatting differs from shfmt's
-w        write result to file instead of stdout
-d …
```
> fix: CI formatting use editorconfig

- docs/plugins-create.md
This PR updates to use v1 plugin-test action instead of v1.0.0 in "Example Github Action" section of document.
ref https://github.com/asdf-community/.github/issues/6
> Use v1 plugin-test action instead of v1.0.0 in document

- test/banned_commands.bats
Add `column` to list of banned commands for the asdf codebase. Tests now pass since https://github.com/asdf-vm/asdf/pull/721 has been merged.
Fixes: https://github.com/asdf-vm/asdf/issues/661 
Related: https://github.com/asdf-vm/asdf/pull/721
> Add `column` to list of banned commands for the asdf codebase

- docs/plugins-create.md
Clarify that shims will be created for files in `$ASDF_INSTALL_PATH/bin` in the docs for the `bin/install` script for plugin authoring.  I got stuck for a bit wondering why my shims weren't being created for a plugin that I was writing for an internal tool. I know this is described in the `bin/list-bin-paths` docs, but I didn't look at those docs since that's an optional script.
Thanks for `asdf`, I think it is going to be very helpful for installation and version management of some of our internal tools!
> Docs: Clarify shim creation for writing plugins

- docs/core-configuration.md
- help.txt
- lib/commands/command-install.bash
- test/fixtures/dummy_plugin/bin/install
- test/install_command.bats
Install one tool specified in .tool-versions
Add a one-argument version of install command `asdf install <name>` that installs that single tool at the version specified in `.tool-versions`.  If there is no `.tool-versions` or if that tool is not in it, an error message is shown and `asdf` exits `1`.
Fixes: #759
> Install one tool specified in .tool-versions

- lib/utils.bash
- test/shim_exec.bats
Add the path to the active `.tool-versions` file on shim errors
```shell
➜ asdf env gcloud            
No version set for command gcloud
Please add one of the following versions in your config file at /home/jthegedus/.tool-versions
gcloud 287.0.0
gcloud 288.0.0
gcloud 293.0.0
asdf-gcloud on  master 
➜ asdf env gcloud
No preset version installed for command gcloud
Please install a version by running one of the following:
asdf install gcloud 290.0.0
or add one of the following versions in your config file at /home/jthegedus/.tool-versions
gcloud 287.0.0
gcloud 288.0.0
gcloud 293.0.0
```
Fixes: #749 
- moved from `echo` to `printf`
- slimmed error output
> fix: print tool-versions file dir on shim error

- docs/core-manage-asdf-vm.md
Revert installation instructions for Homebrew to be commands that append to shell configs instead of the contents to be added. `$(brew --prefix)` will now be computed on adding `asdf` to the shell config instead of being computed on each execution.
Fixes: #771 
This has potential to break when the `asdf` Homebrew package is updated and changes the installation location. The consensus is that we will deal with those issues if/when they arise.
> fix: revert to cmds to precompute brew prefix on addition to shell config

- lib/commands/command-plugin-test.bash
`plugin-test` currently tries to install the plugin without providing a version if `asdf latest` fails.
This emits an error message before instead.
Fixes #756
> fix: plugin test to emit error message when `latest` fails

- README.md
- docs/_sidebar.md
Add links to README and website sidebar to our preferred tools for Q&A and community. GitHub Issues and SO links, GitHub Discussions placeholder.
Fixes: #766 
Re community: from the members who participated in https://github.com/asdf-vm/asdf/issues/766 it seems [GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) will be the best place to keep community interaction as it doesn't introduce another tool (eg Discord) where conversations are hidden, not index-able by Google etc. I am open to further discussion on this, though vote for GitHub Discussions.
> docs: link to our community and place(s) for q&a

- asdf.fish
This makes sure the shims folder is appended to $PATH only once. Before, if the user's $HOME contained a trailing `/` two shims folders would get appended to $PATH (e.g; `/home/lucas//.asdf/shims` && `/home/lucas/.asdf/shim`), preventing the user from using the `system` version as described in #767.
Fixes #767
This pretty much just replicates the logic in this line [https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L24](https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L24
) to the fish script
> make sure the shims folder is appended to path only once

- asdf.fish
Append `/shims` to `$HOME/.asdf` in $asdf_user_shims.
I also had to move the if statement inside `set`, because if you use the `-l` flag inside the scope of a if statement, the variable doesn't become available in the global scope.
Fixes: https://github.com/asdf-vm/asdf/pull/777#pullrequestreview-465867789
```
> echo $PATH | grep asdf
/home/lucas/.asdf/shims /home/lucas/.asdf/bin ...
```
> fix shims folder path

- lib/commands/command-plugin-test.bash
Currently, `asdf plugin-test` checks to see whether the parameter `tool_version` is zero instead of whether the output of `asdf latest` is zero to determine whether or not the plugin reports a latest version number. This change fixes that typo which was likely introduced in #772.
Fixes: n/a
> fix: typo causing plugin-test to erroneously fail

- .github/ISSUE_TEMPLATE/bug_report.md
- completions/_asdf
- completions/asdf.bash
- completions/asdf.fish
- help.txt
- lib/commands/command-info.bash
- test/info_command.bats
Add `asdf info` to enable easier debug info gathering for users.
Fixes: #786 
On my machine this prints:
```shell
.asdf on  master [?] 
➜ asdf info
OS:
Linux win10 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
SHELL:
zsh 5.8 (x86_64-ubuntu-linux-gnu)
ASDF VERSION:
v0.8.0-rc1-d37e99a
ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/jthegedus/.asdf
ASDF INSTALLED PLUGINS:
deno                         https://github.com/asdf-community/asdf-deno.git
firebase                     https://github.com/jthegedus/asdf-firebase.git
gcloud                       https://github.com/jthegedus/asdf-gcloud.git
golang                       https://github.com/kennyp/asdf-golang.git
gradle                       https://github.com/rfrancis/asdf-gradle.git
hadolint …
```
> feat: cmd to print debug information

- lib/commands/command-where.bash
- test/where_command.bats
Fixes a bug with `where` command when multiple versions are selected. See #690 for more information  
Fixes: #690
> fix: _where_ bug when multiple versions are selected

- .gitattributes
This seems relevant now we have users on Windows operating systems (I am one on occasion)
---
~I happy to trim some of these items as I copied from an old project. It seems https://gitattributes.io is down now so I can't grab a new default version.~
> chore: add gitattributes file

- docs/core-manage-asdf-vm.md
This pull request fixes the fish init script.
Currently, the subcommand works when run from bash-like shells but doesn't work from a fish shell.
Now, the subcommand uses `()` instead of `$()`. Also, the interpolated subcommand is now parsed properly as quotes need to be exited from. Using `source /usr/local/opt/asdf/asdf.fish` instead of `source (brew --prefix asdf)/asdf.fish` often saves well over a second when starting a new terminal session.
> fix: fish init command

- lib/commands/command-current.bash
- test/current_command.bats
https://github.com/asdf-vm/asdf/pull/746 introduced a header row for `asdf current` command. This has had downstream affects with tools that rely on the output, eg spaceship prompt as noted here https://github.com/asdf-vm/asdf/pull/746#issuecomment-684042798
This PR comments out that header row for now. We should probably bundle all header rows changes into a single release of `asdf`, eg `0.9.0`, and not fragment the development over two point releases.
> fix: rm asdf current header row for now

- docs/core-manage-asdf-vm.md
Link to #785 in the documentation site in the Homebrew installation section as #749 raised an actual caveat/incompatibility between Homebrew and `asdf` (`homebrew test <brew pkg>` has issues if it depends on an `asdf` installed tool)
Given we now have a legitimate caveat with Homebrew in #794 perhaps we can get usage of the caveat logging on Homebrew installation :thinking:
> docs: link to Homebrew common issues from documentation site

- lib/commands/command-plugin-update.bash
Issue: when asdf is first installed, there are no plugins, and running `asdf plugin-update --all` crashes because the plugin directory doesn't exist; similarly, the command crashes if the plugins directory exists yet doesn't contain any subdirectories.
Solution: This patch changes the directory loop from using a wildcard `plugins/*` to a more robust approach: first verify the plugins directory exists, then use the`find` command to list subdirectories and correctly handle the corner case of no subdirectories.
Future: Consider printing an error message and/or advice message. Consider automatically creating the plugins directory as needed. Consider prompting the user to install some popular plugins.
Fixes: List issue …
> Fix plugin-update --all when there are no plugins

- lib/commands/command-export-shell-version.bash
- lib/commands/version_commands.bash
- test/fixtures/dummy_plugin/bin/list-all
- test/install_command.bats
- test/latest_command.bats
- test/list_command.bats
- test/shim_exec.bats
- test/uninstall_command.bats
- test/update_command.bats
- test/version_commands.bats
Support the version "latest" in the `shell`, `local`, and `global` commands.
This allows running `asdf shell <plugin> latest` to use the latest version of the program installed with the mentioned plugin.
Example:
```
0.45.0
```
Fixes: #801
> feat: support for "latest" in shell, local, and global

- bin/asdf
- bin/private/asdf-exec
- lib/commands/command-current.bash
- lib/commands/command-env.bash
- lib/commands/command-exec.bash
- lib/commands/command-export-shell-version.bash
- lib/commands/command-help.bash
- lib/commands/command-info.bash
- lib/commands/command-install.bash
- lib/commands/command-list-all.bash
- lib/commands/command-list.bash
- lib/commands/command-plugin-push.bash
- lib/commands/command-plugin-test.bash
- lib/commands/command-plugin-update.bash
- lib/commands/command-reshim.bash
- lib/commands/command-update.bash
- lib/commands/command-where.bash
- lib/commands/command-which.bash
- lib/commands/version_commands.bash
- lib/utils.bash
- test/banned_commands.bats
* Add `echo` to list of banned commands.
* Replace `echo` calls with calls to `printf`.
* Correct existing `printf` calls that were generating ShellCheck warnings.
Fixes: #781
> chore: ban echo command

- release/tag.sh
We renamed the documentation to refer to `asdf` the tool itself instead of `asdf-vm`. We forgot to update the release script.
> fix: docs file rename

- help.txt
I was using some other tools earlier this week and found links to the repo and documentation in their `help` command output very useful to discover the separate documentation site without resorting to searching or browsing the repo.
I suggest we add it here to improve the visibility of our own documentation site
> docs: print docs and github URLs in help cmd

- README.md
- docs/_sidebar.md
Updates image references from `icongram.jgog.in` to `icongr.am` URLs
I noticed the broken image in the documentation site sidebar:
As far as I can tell, `icongram.jgog.in` became `icongr.am` (partly based on [this tweet](https://twitter.com/GeekGogari/status/912689871818457090)).
I did a search for references to the old domain and updated them to the new one.
> Update documentation references to icongram svg files

- lib/commands/command-list.bash
- lib/commands/command-plugin-list.bash
- test/current_command.bats
Fixes: Updates error message when no plugins are installed
The previous error message was overly informal
> Update no plugin installed error message

- docs/core-manage-asdf.md
Changed install directions as the ohmyzsh asdf plugin has been updated to support Homebrew and completion from ohmyzsh/ohmyzsh#6749.
> docs: improve zsh completion directions for macOS,ZSH,Homebrew

- README.md
- docs/_sidebar.md
Adds links to GitHub Discussions in the *Community & Questions* section of README and Sidepane of docs site
> docs: github dicsussions link

- lib/utils.bash
- test/shim_exec.bats
Process substitution isn't specified by POSIX and makes shims break when called by a script that `export POSIXLY_CORRECT=1` (like gitflow [here](https://github.com/nvie/gitflow/blob/develop/git-flow#L78)).
Here we replace `grep -f <(cmd1) <(cmd2)` with `cmd2 | grep -F "$(cmd1)"` so that we can provide a string instead of a file descriptor and get the same result as before.
(Note: We also check if the result of `cmd1` is empty before running `grep` to get the same behavior as with `-f`. This also prevent crashes if null results are piped to `xargs` and fits nicely with the `with_shim_executable` function that already check the result of `$selected_version` [here](https://github.com/asdf-vm/asdf/blob/master/lib/utils.bash#L729) before going on).
Fixes: #581
The test case is from @tejanium …
> fix: shims break when POSIXLY_CORRECT=1

- CONTRIBUTING.md
Fixes a broken link in the CONTRIBUTING.md, the same as here #835, but different file.
> fix: broken link in contributing.md

- lib/commands/command-plugin-update.bash
When updating plugins, I've gotten this warning:
```
find: warning: you have specified the global option -mindepth after the argument
-type, but global options are not positional, i.e., -mindepth affects tests
specified before it as well as those specified after it.  Please specify global
options before other arguments.
find: warning: you have specified the global option -maxdepth after the argument
-type, but global options are not positional, i.e., -maxdepth affects tests
specified before it as well as those specified after it.  Please specify global
options before other arguments.
```
Change find options position on `lib/commands/command-plugin-update.bash`
If there is anything else that is relevant to your pull request include that
information here.
> Fix find global options warning

- docs/core-configuration.md
The difference between `$ASDF_DIR` and `$ASDF_DATA_DIR` tripped me up while getting set up, so I added it to the docs. 
Fixes: None
Your project makes mantaining my projects much easier, and I really appreciate that. Thanks!
> docs: explain ASDF_DIR

- docs/contributing-core-asdf.md
Fixes link to bats-core repo instead of deprecated version.
> docs: update bats link to bats-core org

- docs/core-manage-asdf.md
At the moment, the fish installation instructions copy the completions to the ~/.config/fish/completions directory.
Having tried this locally, a symlink works just as well.
Could it be worth symlinking to bring along any future updates to the completions file?
> docs: fish symlink completions rather than copying

- docs/core-manage-asdf.md
Z shell supports placing your zshrc file in an alternate location, such as inside `.config` (which makes it far more conveninent to store your dot files in a Git repo, or even just sync them across machines with other folder-oriented synchronization tools).  
The current command assumes the default location of putting the rc file directly in the home directory.  But it is easy enough to support all alternate locations as well.  This version defaults to `~` if the variable `ZDOTDIR` is not defined.
I'm only including the case I've tested in this PR, but if you want me to do the same thing for other shells and other cases with Zsh, I'm open to doing that too.
If there is anything else that …
> Support alternate location for .zshrc

- docs/_navbar.md
The "language translation" section is somewhat diffcult to find, this addition makes it easily accessible even from the homepage.
Added a single line.
> docs: button for adding new translations

- docs/core-configuration.md
The documentation of the ASDF_DEFAULT_TOOL_VERSIONS_FILENAME environment variable wasn't very clear. Clarifying that it must be a filename and not a file path should help with issues like #900.
> docs: clarify usage of ASDF_DEFAULT_TOOL_VERSIONS_FILENAME

- docs/core-manage-versions.md
Fix the section heading level for "By-passing asdf shims" at https://asdf-vm.com/#/core-manage-versions?id=by-passing-asdf-shims .
- The text for H6 was extremely small - much smaller than the normal paragraph text. The font-size for the h6 was 9px. It looked incredibly small and silly. This fix will make the heading bigger, which may be against the original intention to keep this section small and out of the way, but honestly the way it looked was really silly and hard to read.
- The heading level wasn't consistent (was too deep relative to the heading structure), which may or may not be an accessibility issue. This isn't the important part though, just a common sense choice to fix the above issue about the font size.
Fixes: Ad-hoc (no issue)
There may be a related issue where h6 …
> Fix tiny text for "By-passing asdf shims" heading

- completions/_asdf
- completions/asdf.bash
I am trying to add the "system" parameter for completion, in bash and zsh.
This present solution is similar to how it is done in fish, basically appending the "system" option at the end of the present versions. Because some options (shell, local, global) need this, but others such as uninstall do not need a "system" version in their completions, I was not able to do it elegantly. I had to split the completion code for the commands that do require system, and commands that do not require system.
This solves issue #868.
> fix: consistent system completion

- lib/commands/command-plugin-update.bash
Some people are having issues with the implementation of #800 
The issue seems to be the `awk` command, specifically the usage of `-F'[[:space:]]*'`.
>awk already splits by multiple spaces by default so we should not override this option
stated here https://github.com/asdf-vm/asdf/issues/899#issuecomment-816374482
Fixes: #899
Fixes: #919
> fix: plugin update portability

- docs/core-manage-versions.md
Document `system` version usage in the "manage versions" doc page. 
Fixes: #868
This came about as I stated in https://github.com/asdf-vm/asdf/issues/868#issuecomment-787530624:
>We do list `system` on this page - asdf-vm.com/#/core-configuration?id=tool-versions
>But it should probably also be mentioned on this page too - asdf-vm.com/#/core-manage-versions
The OP of the issue PRd the tab completion fix for system on ZSH and Bash completions as the other part of this.
> docs: describe using the system version

- docs/core-manage-asdf.md
Delete instructions to add dependencies with Homebrew
Fixes: #936
> fix: delete instructions to add dependencies with Homebrew

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Issue and PR reporters often do not remove the instructions from the template before submitting. This fixes that issue by commenting them out. They are visible when creating the issue, but do not require deletion before submission and do not pollute the Issue/PR for the readers.
> chore: comment out instructions in issue/pr templates

- .github/workflows/workflow.yml
Currently our PRs run 2 sets of the workflow for each of the `push` and `pull_request` events. We should only run one set of events on PRs which should be the PR events. Push events can run on `master` only.
I don't think this changes any developer workflows (observing push builds before opening PRs), but please discuss if this impacts your experience.
I also removed the cron execution as it is not really adding value.
> ci: push-event triggers CI only on master branch

- .github/workflows/tests.yml
A hotfix so the CI checks on `master` will remain green by not running the known-failing WSL1 workflow on master.
> ci: do not run WSL1 jobs on master

- .github/workflows/lint.yml
- release/README.md
- scripts/shellcheck.bash
- scripts/shfmt.bash
Revert changes to local workflows from #956
> fix: lint scripts for local and CI

- docs/core-manage-asdf.md
Pacman requires a 4th step to remove `asdf` properly so the previously common step needs to be moved into each option.
> docs: rm duplicate text from asdf remove section

- docs/core-configuration.md
- lib/utils.bash
- test/plugin_list_all_command.bats
Add update plugins repo function to `asdf plugin-update` command that can be get latest asdf plugins list
Hi everyone,
I tried to update the asdf plugins today,
but I didn't get latest plugins list.
I can't find a way to update asdf plugin list, 
so I implement this function in plugin update command.
I think about plugin update command for user flow,
When user want to update plugin, 
they maybe want to get latest plugin list,
so I add trigger function on plugin update command.
I hope to help this project to be better.
Thanks.
> feat: configurable plugin repo last check time

- docs/core-manage-plugins.md
- explain plugin repo syncing and that it is configurable
- add missing explanations for each add, update, remove plugin ops as they are listed in `asdf help` but not in the docs
I also started refering to the plugin repo as the "short-name" repo as it seems people are confusing this as the only way to install plugins. This is going as far as requests to customise the plugin repo location which is completely unnecessary when you can add via Git URL. Refering to it as the short-name repo, hopefully will indicate this isn't the sole plugin repo. Though, this is just a fix of a symptom and not the cause IMO.
I also swapped the docs order so adding via Git URL comes first as it is the better method for people to use.
Fixes: #946
> docs: explain plugin repo sync details

- docs/core-manage-asdf.md
Fixes the instruction for sourcing asdf for Linux,Fish,Pacman.
It currently says to source the `.sh` file instead of the correct `.fish` one.
> fix shell config command for Linux,Fish,Pacman

- .github/ISSUE_TEMPLATE/config.yml
This will add an option in the New Issue selection (https://github.com/asdf-vm/asdf/issues/new/choose) to select a "question" type which will direct people to our GitHub Discussions
The goal being reduction in Issues that are merely questions/clarifications.
> chore: question Issue type & direct to GH Discussions

- help.txt
I missed the help text updates in my #633 conflict resolution.
Related to #633
> fix: help text as per new feats in #633

- lib/commands/command-reshim.bash
- lib/utils.bash
- test/reshim_command.bats
- test/test_helpers.bash
If `ASDF_DATA_DIR` has a space in the path (by default, this means `asdf` itself was installed to a path with a space), then the shims will not be created correctly in bash.  This PR fixes the issue.
I have only checked up to the actual executable (in my case, node) running — I do not yet know if there are other issues related to spaces in the path.
I'm using extra variables for the lists (which contain newlines) because POSIX shell wouldn't support `while read … done; while < <(command)` (and is caught by the tests).
> fix: ensure shims get created when data dir has spaces

- .github/workflows/tests.yml
Removing the WSL1 test environment from the CI workflows. This was raised in #963 and then causing confusion to contributors in #996, which was not the intent.
I still think in we should have test cases for environments we want to support, otherwise there is no drive to resolve the issues causing the errors. Nonetheless, WSL1 isn't an environment we wish to target. WSL2 is, but there is no support for it in any GitHub runner to date (AFAICT).
Hopefully the code removed in the diff is helpful to whomever eventually implements WSL2 test support.
> ci: remove WSL1 test env

- docs/.vuepress/config.js
- docs/.vuepress/navbar.js
- docs/.vuepress/sidebar.js
- docs/manage/versions.md
- docs/pt-BR/guide/getting-started.md
- docs/pt-BR/guide/introduction.md
- docs/pt-br/contribute/core.md
- docs/pt-br/contribute/documentation.md
- docs/pt-br/contribute/first-party-plugins.md
- docs/pt-br/contribute/github-actions.md
- docs/pt-br/guide/getting-started.md
- docs/pt-br/guide/introduction.md
- docs/pt-br/index.md
- docs/pt-br/learn-more/faq.md
- docs/pt-br/learn-more/thanks.md
- docs/pt-br/manage/commands.md
- docs/pt-br/manage/configuration.md
- docs/pt-br/manage/core.md
- docs/pt-br/manage/plugins.md
- docs/pt-br/manage/versions.md
- docs/pt-br/plugins/create.md
This is a follow up to #1000 adding the pt-br translations from @Rogerio-Viana in #970 back to the new site.
I copied over content from the old docs as best I could. Instead of leaving un-translated pages blank I copied over the English page and added a comment to the top of the page.
>Hi, we've recently migrated our docs and added some new pages. If you would like to help translate this page, see the "Edit this page" link at the bottom of the page.
The Introduction and Getting Started pages are the ones which need entire rewrites, as with the Contribution pages. I am sorry @Rogerio-Viana that this migration didn't happen before you put in the huge effort to translate. I hope this is a good start for you and others to build upon :pray:
`docs/.vuepress/navbar.js` and …
> docs: pt-br translation migration

- docs/contribute/core.md
Fix rendering issue. The items should be a list, as markdown renders singularly newlined paragraphs as the same paragraph.
> docs: use list so rendering isn't merged

- lib/commands/command-info.bash
`asdf plugin list --refs --urls` in `asdf info` command output
Fixes: #945
> feat: display plugin repo refs alongside urls in info cmd

- docs/manage/configuration.md
- lib/utils.bash
- test/plugin_list_all_command.bats
This builds on #957 by allowing the plugin shortname repo sync to be toggled off completely with:
```
plugin_repository_last_check_duration = never
```
Fixes: #978 
<details>
<summary>Docs changes comparison</summary>
</details>
> feat: toggle off repo sync completely

- docs/guide/introduction.md
Fixes: A couple of gramatical mistakes in the intro guide
> docs: Fix typos in introduction.md

- docs/manage/plugins.md
The previous link was to a plugin template. Updated to point to a list of plugins. (I think this is the right place?)
> docs: Update the link to the Plugin Shortname Index

- lib/utils.bash
Message displayed when executing a command that does not specify a version, and the error message is output at the same time because of incorrect usage of grep.
Extract from macOS man:
> -F, --fixed-strings
>        Interpret pattern as a set of fixed strings (i.e. force grep to behave as fgrep).
> -f file, --file=file
>        Read one or more newline separated patterns from file.  Empty pattern lines match every input line.  Newlines are not considered part of a pattern.  If file is empty, nothing is matched.
Expected:
```shellscript
> go
No version set for command go
Consider adding one of the following versions in your config file at 
go-sdk 1.17
```
Actual(in head branch):
```shellscript
> go
grep: go-sdk 1.17
go-sdk system: No such file or directory
No version set for command go …
```
> fix: incorrect usage of grep

- lib/commands/command-latest.bash
This fixes the following error with sed on FreeBSD:
```
sed: 1: "s/^\s\+//": RE error: trailing backslash (\)
```
Fixes: #1046
I confirmed the command still works as expected on Linux and macOS.
> fix: sed re error trailing backslash on FreeBSD (#1046).

- lib/commands/command-plugin-update.bash
- test/plugin_update_command.bats
In `asdf plugin update --all`, `wait` is not working and the command exits before the update of each plugin are finished.
Executing `while` after a pipe will run it in a subshell, so you can't use `wait` on the caller to wait for each command to finish.
In such a case, *Process Substitution* is often used, but it seems to be prohibited in this project.
However, for the usage here, I think *Here string* is fine.
> fix: wait until the plugin update are finished

- lib/commands/command-help.bash
- test/plugin_extension_command.bats
When a plugin with a hyphen in its name contains an extension command (lib/commands/commands-*), the - in the plugin name displayed by asdf help will be blank.
Fixes: #1034
> fix: help for extension commands for plugins with hyphens in the name.

- docs/plugins/create.md
- lib/commands/command-plugin-update.bash
- test/fixtures/dummy_plugin/bin/post-plugin-update
- test/plugin_update_command.bats
Currently, asdf does not have a hook that is called when a plugin is updated, so it is not possible for plugins to perform migrations.
For example, if a plugin has a problem and needs to be fixed under "installs", the only way to do this is to have the user do it after installation.
With the post-install-hook, it will be possible to migrate when updating, which will make it easier to develop plug-ins and improve the usability for users.
This may also answer the request of #859 .
> feat: add post update plugin support

- docs/guide/getting-started.md
Corrects minor grammar error in docs.
> docs: Remove stray `a`

- docs/manage/core.md
- docs/pt-br/manage/core.md
Currently, the brew upgrade from latest commit on master command is specified like `brew upgrade asdf --HEAD`, which is incorrect, failing with 
`Error: invalid option: --HEAD`.
The correct option is [--fetch-HEAD](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/upgrade.rb#L57)
Fixes: display the correct command:
`brew upgrade asdf --fetch-HEAD`
> docs: fix brew upgrade from latest commit on master command

- lib/commands/command-install.bash
- test/install_command.bats
When calling the install command, asdf tries to look for versions for all the plugins available and installs them. With this change, it will attempt to find versions for all the installed plugins and plugins defined in the `.tool-versions`.
Fixes https://github.com/asdf-vm/asdf/issues/574
> feat: Displays a warning when a plugin from the tools-version list does not exist

- lib/commands/command-plugin-test.bash
Quote variables correctly in `command-plugin-test.bash`, eliminating bizarre results when trying to run commands with whitespace in them.
Before:
```
% asdf plugin-test bundler https://github.com/jonathanmorley/asdf-bundler.git 'bundler --version | grep 2.2.29'
Updating bundler...
Already on 'master'
Your branch is up to date with 'origin/master'.
ERROR: "bundler version" was called with arguments ["|", "grep", "2.2.29"]
Usage: "bundler version"
FAILED: bundler --version | grep 2.2.29 failed with exit code 0
```
After:
```
% ./bin/asdf plugin-test bundler https://github.com/jonathanmorley/asdf-bundler.git 'bundler --version | grep 2.2.29'
Updating bundler to master
Already on 'master'
Your branch is up to date with 'origin/master'.
Bundler version 2.2.29
```
The intended behavior was …
> fix: Quote commands correctly in plugin-test

- asdf.sh
- test/version_commands.bats
Allow users to define their own value of ASDF_DIR before sourcing asdf.sh, e.g. when it was installed with homebrew.
For example, I can use this in my shell startup script:
```
ASDF_DIR=/usr/local/opt/asdf
source "$ASDF_DIR/asdf.sh"
```
Also, similar test for `[ -z "$ASDF_DIR" ]` is already being done in `lib/utils.bash`.
Also unset locally used variables at the end.
> fix: don't override existing ASDF_DIR

- lib/commands/command-plugin-test.bash
- test/fixtures/dummy_plugin/LICENSE
- test/plugin_test_command.bats
> fix: Fix plugin-test arg parsing

- docs/manage/configuration.md
Closes #1091
This includes a brief mention of, and some simple examples, of comments in `.tool-versions` files.
This fixes issue #1091.
> docs: Mention comments for `.tool-versions` files

- lib/commands/command-current.bash
- lib/utils.bash
- test/current_command.bats
- test/shim_exec.bats
- test/where_command.bats
"no version set" can read as a noun, this confused someone I work with
recently :)
> fix: clarify the wording when no version is set

- lib/commands/command-help.bash
- lib/utils.bash
* fix: Use bash instead of sed for updating PATH environment variable
* fix: Remove unnecessary ls and sed commands
Fixes: #686
> fix: Sed improvements

- .github/ISSUE_TEMPLATE/bug_report.yaml
Instructs bug reporters to use correct `asdf info` command.
Fixes: #1105
> docs: fix bug report info instructions

- lib/commands/command-plugin-add.bash
The version of grep that is shipped with alpine doesn't seem to support "long name" options
> fix: shorthand grep options for alpine support

- lib/commands/command-help.bash
Do not print errors `find` command produces when no `lib/commands` exists under plugin directories.
Fixes: #1101 
Example output from `asdf help` on the current master branch.
```
...
RESOURCES
GitHub: https://github.com/asdf-vm/asdf
Docs:   https://asdf-vm.com
find: ‘/home/_/.asdf/plugins/deno/lib/commands’: No such file or directory
PLUGIN direnv
asdf direnv
asdf direnv hook asdf
find: ‘/home/_/.asdf/plugins/nodejs/lib/commands’: No such file or directory
find: ‘/home/_/.asdf/plugins/python/lib/commands’: No such file or directory
find: ‘/home/_/.asdf/plugins/ruby/lib/commands’: No such file or directory
find: ‘/home/_/.asdf/plugins/terraform/lib/commands’: No such file or directory
"Late but latest"
-- Rajinikanth
```
After applying this fix.
```
...
RESOURCES
GitHub: …
```
> fix: do not print `find` errors

- lib/commands/command-latest.bash
- test/latest_command.bats
As discussed in #1036, this patch adds a `--all` flag to the latest command which will show the list of plugins, their latest version and if this one is installed or not.
Fixes: #1036
This patch basically reuses the logic used in the list command and the latest command. The main different is the removal of the query parameter as different plugins might need different queries.
> feat(latest): adds the flag --all to the latest command

- test/banned_commands.bats
Fixes #1109
Rather than just having one array of both literal commands and regex patterns, I split the banned commands into two arrays - one of literal commands and one of regex. This allows us to use the `-E` (extended regex) option when looking for banned commands via regex.
> fix: ban grep long flags

- help.txt
- lib/commands/command-latest.bash
- test/latest_command.bats
Fixes the bug reported at #1096. Uninstalled plug-ins are now marked as missing. The plug-in will be marked as installed only if the latest version is among the installed plug-ins.
Fixes: #1096
> fix: latest --all correctly report plugins as missing

- lib/commands/command-reshim.bash
- lib/commands/reshim.bash
- lib/commands/version_commands.bash
Signed-off-by: JrCs <90z7oey02@sneakemail.com>
If the replacement (sed) is not done the backup file isn't create and the rm command return on error.  
With `rm -f` no error is generated even if the file doesn't exists.
> fix: don't generate on error if backup file doesn't exists

- lib/commands/command-latest.bash
- test/fixtures/dummy_legacy_plugin/bin/list-all
- test/latest_command.bats
- test/version_commands.bats
The `asdf latest` command currently only filters unstable versions with lowercase version suffixes (`alpha`, `pre`, `snapshot`, etc.) but fails if there are version suffixes using uppercase.
This is currently happening with the [asdf-kcctl](https://github.com/joschi/asdf-kcctl) plugin.
> feat: case-insensitive filtering of unstable versions in `latest`

- lib/commands/command-install.bash
- lib/commands/command-latest.bash
- lib/commands/command-list.bash
- lib/commands/command-plugin-list-all.bash
- lib/commands/command-plugin-list.bash
- lib/commands/command-reshim.bash
- lib/utils.bash
- test/banned_commands.bats
`ls` should be banned because it's seldom the right tool for the job. Often plain old shell globbing, or `find` are more reliable ways of listing directories. 
* Only grep sh/bash files for banned commands
* Ban `ls` command
* Replace instances of `ls` with `find`
Related: https://github.com/asdf-vm/asdf/pull/1100 https://github.com/asdf-vm/asdf/issues/1029
Fixes: Uncertain whether this will fix any outstanding issues.
> fix: Ban `ls` command

- help.txt
The help text was 
```
…
asdf local <name> latest[:<version>]    Set the package local version to the
latest provided version
asdf global <name> <version>            Set the package global version
asdf global <name> latest[:<version>]   Set the package local version to the
latest provided version
…
```
This PR updates the help text for `asdf global <name> latest[:<version>]` to:
```
asdf global <name> latest[:<version>]   Set the package global version to the
latest provided version
```
> docs: Fix help text for 'asdf global'

- asdf.sh
- test/asdf_sh.bats
`asdf` [v0.9.0][1] included a [bug fix][2] to not override an existing `ASDF_DIR`.
However, if `ASDF_DIR` is not set at all, then this causes an error when using bash `set -u`, or `set -o nounset` - see [here][3] for additional info.
`asdf.sh: line 6: ASDF_DIR: unbound variable`
Edit: see also #160 and #817
[1]: https://github.com/asdf-vm/asdf/releases/tag/v0.9.0
[2]: https://github.com/asdf-vm/asdf/pull/1008
[3]: https://mywiki.wooledge.org/BashFAQ/112
> fix: Prevent unbound variable error with nounset in asdf.sh

- asdf.elv
Prepends `~/.asdf/bin` and `~/.asdf/shims` to the `PATH` environment variable (instead of appending them). This is consistent with the other shell integrations.
While I was at it, I also sorted the imports alphabetically, used [tilde expansion](https://elv.sh/ref/language.html#tilde-expansion) instead of `$E:HOME`, and removed an unnecessary semicolon.
> fix(elvish): prepend asdf paths to `$PATH`

- .github/ISSUE_TEMPLATE/config.yml
- docs/.vuepress/navbar.js
- docs/.vuepress/sidebar.js
Github Discussions seems to have been disabled, removing it from documentation
> docs: remove github discussion reference

- .tool-versions
- lib/utils.bash
This change uses 1 call to `sed` for the whole `.tool-versions` file instead of for each line. This can substantially speed up file parsing if there are many comments in a file. I also had an issue with the current root `.tool-verisons` file not installing `bats` correctly because of the leading `v`.
This fixes issue #1195.
Changes:
* Remove comments from whole `.tool-versions` at once instead of line by line for performance
* Remove the leading `v` from the root `.tool-versions` file to help asdf resolve it correctly.
> fix: remove comments from whole file instead of line by line for performance

- lib/commands/command-help.bash
- lib/commands/command-list.bash
- lib/commands/command-plugin-push.bash
- lib/commands/reshim.bash
- lib/functions/installs.bash
- lib/functions/plugins.bash
- lib/functions/versions.bash
- test/list_command.bats
Fixes part of #1029
The shell glob pattern `dir/*` matches any files in `dir/`, `dir/*/` matches only directories in `dir`. When iterating over the plugins directory we only care about directories, since only they can represent plugins.
> fix: only iterate over directories in the plugins/ directory

- .github/workflows/docs-version.yml
Possible fix for https://github.com/asdf-vm/asdf/issues/1230
@jthegedus I based this off of https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10. I haven't been able to test it yet.
> fix: update event trigger for doc-version workflow

- lib/functions/versions.bash
- lib/utils.bash
- test/version_commands.bats
Fixes #1082
Tests are failing for some reason locally and I'm not sure why.
> fix: always use ASDF_DEFAULT_TOOL_VERSIONS_FILENAME for filename when present

- README.md
While clicking on a few links to test for including in our [Ruby on Rails community survey results](https://rails-hosting.com/2022/)and noticed that the links to the previous URLs like https://asdf-vm.github.io/asdf/plugins/create.html were resulting in a 301 Redirect to http://asdf-vm.com/plugins/create.html, which would show a "Not Secure" warning in the browser.
I went ahead and updated all these references to just go directly to https://asdf-vm.com/... 
Fixes: No existing issues found for this
You might want to look at your legacy github.io site redirect logic, too, so that external links get sent to the SSL site, too.
> fix: updating references to legacy github.io site

- lib/functions/plugins.bash
- test/plugin_add_command.bats
[:alpha:] and [:digit:] character classes support characters from other
languages whereas ranges like a-z and 0-9 may not.
Fixes #1237
> fix: update plugin-add regex to support other languages

- lib/utils.bash
`asdf_data_dir` function inits `ASDF_DATA_DIR` with `HOME` when value is empty.
`HOME` may replace to empty string when asdf shims called by non-shell program.
this makes invalid value of `ASDF_DATA_DIR`.
the PR fixes this issue by use `asdf_dir` function instead of call environment variable.
I faced this issue when using `hugo` which installed by [nklmilojevic/asdf-hugo](https://github.com/nklmilojevic/asdf-hugo) and nodejs which installed by [asdf-vm/asdf-nodejs](https://github.com/asdf-vm/asdf-nodejs) like this:
```shell
$ hugo server
Start building sites … 
hugo v0.91.2-1798BD3F linux/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio
Error: Error building site: POSTCSS: failed to transform "style/style.css" (text/css): unknown command: npx. Perhaps you have to reshim?
Built in …
```
> fix: get invalid ASDF_DATA_DIR when exec asdf shims by non-shell

- docs/plugins/create.md
While the sentence is correct we do not want users relying on `utils.bash` internal functions
Related to the conversation on #682
> docs: remove text from plugin create doc that says utils.bash functions are available

- .github/dependabot.yml
Dependabot can be configured via YAML to control the frequency of when it scans and raises PRs
Here it is configured to scan for:
- `docs/` directory for `npm` vulnerabilites.
- GitHub Actions for updates to the Actions used in Action Workflows themselves
I also assign myself as reviewer to not spam everyone else, we will see if this overrides the config in `.github/CODEOWNERS` which automatically applies the `asdf/core` team as reviewers, hopefully it does override.
The update schedule is set to `weekly`:
>When you set a `weekly` update schedule, by default, Dependabot checks for new versions on Monday at a random set time for the repository - [quote from docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file# …
> ci: configure dependabot scanning & PR generation

- .github/workflows/tests.yml
- .tool-versions
- test/asdf_fish.bats
- test/banned_commands.bats
- test/get_asdf_config_value.bats
- test/help_command.bats
- test/install_command.bats
- test/plugin_add_command.bats
- test/plugin_extension_command.bats
- test/plugin_list_all_command.bats
- test/plugin_remove_command.bats
- test/remove_command.bats
- test/reshim_command.bats
- test/shim_env_command.bats
- test/uninstall_command.bats
- test/update_command.bats
- test/utils.bats
- test/version_commands.bats
- test/which_command.bats
- Run tests in more environments, testing the latest and capturing regressions on existing supported systems.
- I am not sure how useful this actually would be. We do often get weird reports from people using older versions on Ubuntu. I am open to changing this to `latest` for each of Ubuntu & macOS.
- bump BATS version.
- bump Shellcheck version.
- bump Shfmt version.
The large diff is from `shfmt` updating single whitespace chars.
> ci: add latest OSs to testing matrix, bump BATS, shfmt, shellcheck

- test/asdf_elvish.bats
This test exists for `fish` and for `sh`, may as well add it for `elvish`.
> fix: add missing "does not add paths to PATH more than once" test for elvish

- .github/workflows/tests.yml
This will make it easier to bump to elvish v0.19.0 whenever that gets released.
> fix: use ELVISH_VERSION to specify elvish test version

- docs/contribute/core.md
Document the approach taken to `.gitignore` list. This was raised in PR #1277
Screenshot of the additional docs section:
The "see here" link is http://stratus3d.com/blog/2018/06/03/stop-excluding-editor-temp-files-in-gitignore
> docs: instruct global ignore file policy

- defaults
- docs/manage/configuration.md
This is a follow up to #1227 to document behaviours further as noted in https://github.com/asdf-vm/asdf/pull/1227#issuecomment-1168043995
- note that `plugin_repository_last_check_duration` does not stop initial repo sync
- note that `disable_plugin_short_name_repository` does not remove the plugin repo if it has already been synced. Document how to remove the plugin repo if the user desires.
- consolidate the `~/.asdfrc` example file contents under the repo root `defaults` file and inline file itself.
> docs: further notes on disabling plugin repo

- docs/guide/getting-started.md
Update the version in the Getting Started guide to `0.10.2`.
This is would have been corrected by #1293 with the next release, but this will get new non-homebrew users onto the latest release, instead of the apr2022 release.
> docs: manually update version to 0.10.2

- test/update_command.bats
Wrap uses of `git tag` output with a check to see if there's a value...
Fixes: #1288 
Tested here: https://github.com/check-spelling/asdf/actions/runs/2660784666
> ci: tolerate the lack of tags in the repository

- help.txt
The MANAGE PACKAGES section of the help text has the commands grouped based on intent and not alphabetically. It may or may not be on purpose, but all other sections are alphabetical, so this seems out of place and can be confusing.
Feel free to close if this is not agreeable.
> chore: alphabetise help txt manage packages section

- lib/functions/versions.bash
Fixes: https://github.com/asdf-vm/asdf/issues/1306
> fix: excludes "milestone" releases in "latest" command

- docs/.vuepress/config.js
- docs/.vuepress/navbar.js
- docs/.vuepress/sidebar.js
- docs/package-lock.json
- docs/package.json
Bump Vuepress v2 to latest Beta. This beta uses the latest version of Vite.js which now defaults to ESM, so we have changed the file imports/exports here too and why I did not merge the dependabot PRs.
Closes the following:
- #1322
- #1323
- #1324
- #1325
I really wish we could get rid of the `package-lock.json` file from this repo. I may consider changing the required system dev dep from Node.js to Deno which would remove `package.json` etc.
> chore: bump docs deps & use esm format

- asdf.fish
Instead of modifying the PATH variable directly, use `fish_add_path` utility function provided by fish.
`fish_add_path` documentation: https://fishshell.com/docs/current/cmds/fish_add_path.html
Use `--global` option to modify only current session.
Use `--move` option to move the paths to front of other items in the path instead of keeping them on the previous position if already in the path.
> refactor: use `fish_add_path` during fish setup if available

- completions/asdf.bash
Various bash completion improvements.
See individual commits for details.
> feat(completions): bash improvements

- test/asdf_elvish.bats
- test/asdf_fish.bats
- test/asdf_sh.bats
On the tests verifying if the path items are not added multiple times to PATH when asdf is sourced twice, instead of checking the resulting PATH, the tests were checking the current terminal PATH
> test: use resulting PATH on duplicated source tests

- lib/utils.bash
- test/banned_commands.bats
This bans the use of `test`. `test` is functionally an alias of `[`; this improves codebase consistency and parseability.
Partially addresses #1313, and is related to #1349
> fix: Ban use of 'test'

- docs/guide/getting-started.md
This can generally avoid complications due to installing under a package manager (homebrew, etc).
Related: https://github.com/asdf-vm/asdf/issues/1387
> docs: improve promotion of git install method

- lib/functions/plugins.bash
- scripts/format.bash
- scripts/shellcheck.bash
- scripts/shfmt.bash
In #1313 I ran some analysis of our Shellcheck errors with the Shell set explicitly to POSIX. Having done this I thought it might be worth updating our `scripts/*` to explicitly check specific files for specific Shell adherence (something discussed in #1313).
What I discovered was that we were not testing some files or dirs, and also setting `bats` in Shellcheck introduced a whole set of errors which have clearly been missed with auto-detection.
~What I want with regards to review discussion is whether we actually capture `asdf.sh` as a POSIX file or whether we should capture it in the `.bash` linting? If we consider it Bash, should we rename it `asdf.sh -> asdf.bash`? Same applies to `/lib/asdf.sh`~
- we're still using 2-space indent 🤮 
Related: #1313, #1349
> ci: explicitly set shell in lint & format scripts

- docs/guide/getting-started.md
- docs/manage/core.md
- docs/pt-br/guide/getting-started.md
- docs/pt-br/manage/core.md
- docs/zh-hans/guide/getting-started.md
- docs/zh-hans/manage/core.md
When using Homebrew on Linux with Bash, as the linked issue states, instructions should specify to put `asdf` initialization in `.bashrc` instead of `.bash_profile. This implements that recommendation.
Fixes: #1347
> docs: Add documentation for Linux Homebrew Bash installs

- scripts/checkstyle.py
This fixes an issue I mentioned in #1406, [here](https://github.com/asdf-vm/asdf/pull/1406#issuecomment-1367642291). Now, the `checkstyle.py` script runs with Python `3.6.15`
> fix: Do not use type not exported on older Python versions

- lib/functions/versions.bash
We need to add trailing newlines to .tool-versions file before appending a new version to the file. The order of the checks was wrong here as the first check assumed the file existed, and the second checked if it did. Switching them fixes the issue.
This fix was provided by @h3y6e
Fixes #1417
> fix: correct order of checks in conditional for adding a missing newline

- .github/workflows/tests.yml
As mentioned [here](https://github.com/asdf-vm/asdf/pull/1403#issuecomment-1372163612), we encountered a [brownout for Ubuntu 18.04](https://github.com/actions/runner-images/issues/6002). This fixes that
> ci: Stop using Ubuntu 18.04

- test/asdf_elvish.bats
Old versions of Elvish cause spectacular failures
My patches fix that:
The module handling was also improved. Rather than copying the `adsf.elv` file and munging with user config files (which was already broken in cases where `$XDG_CONFIG_HOME` was not set to `$HOME/.config`), it uses the files in place by using relative imports. Additionally, `XDG_CONFIG_HOME` and `XDG_DATA_HOME`, etc. were set to empty so user config files are never parsed (it seems the `-norc` flag of Elvish is limited), improving test isolation.
> test: Improve Elvish tests

- docs/guide/getting-started.md
- scripts/update_version_in_docs.bash
The previous one was out of sync with the current doc formatting.
> ci: fix regex in `update_version_in_docs.bash` script

- test/asdf_elvish.bats
- test/current_command.bats
- test/install_command.bats
- test/remove_command.bats
- test/shim_exec.bats
- test/version_commands.bats
This PR is the **first** of a [multi-part series](https://github.com/asdf-vm/asdf/compare/master...hyperupcall:asdf:shellcheck-tests) that fixes various issues with the tests. I broke this change up as to be easier to review, and it seemed similar to #1349, in which different PRs were preferred over a single larger one.
Here is a description of each commit/part:
- ~~Parts 1-5 are quite trivial and fix up obvious mistakes like quoting.~~
- Parts 1 does a few miscellaneous fixes
- Parts 2-5 are quite trivial and fix up obvious mistakes like quoting.
- Part 6 has the first non-obvious changes that remove use of `$?` by using the `run` function provided by Bats 
- Part 7 fixes all errors and warnings shown by Bats. The significant code change is that some regex comparison were changed to glob …
> chore: fix ShellCheck errors in tests

- test/test_helpers.bash
[According to Bats](https://github.com/bats-core/bats-core/releases/tag/v1.7.0), the just-merged usage of `setup_suite.bash` was added in Bats 1.7. Conveniently, a `bats_require_minimum_version` was also added to assert the minimum Bats version.
This uses that, partially addressing #1435  
The assertion must be in `test_helpers.bash`, because versions under 1.7 won't even automatically source `setup_suite.bash`, making the assertion useless
> test: vaidate Bats minimum required version in tests

- scripts/checkstyle.py
General fixes for `checkstyle.py`, including a false positive fix for the `no-test-double-equals` rule.
> chore: improve checkstyle double equals test regex & types

- test/asdf_fish.bats
In the same style as #1423 and #1422, this only runs Fish tests if Fish is installed
Partially addresses #465 (part of the WSL errors are Fish not installed errors, even if the error isn't WSL-specific)
> test: Skip Fish test if not installed

- lib/utils.bash
- scripts/checkstyle.py
- test/utils.bats
- test/where_command.bats
In Bash, there are there ways to declare a function:
```sh
fn() { :; }
function fn { :; }
function fn() { :; }
```
This PR ensures that only the first form is used.
> fix: enforce & use consistent function definitions

- asdf.nu
- test/asdf_nu.bats
Ever since Nushell v0.75.0 was released on homebrew, our CI fails (see #1479, #1480, and #1482). This fixes the Nushell tests to be compatible with the latest version
The only necessary change is the `export extern "asdf"` => `export extern main`, which is due to [recent module changes](https://www.nushell.sh/blog/2023-01-31-nushell_0_75.html#main-command-exported-from-module-defines-top-level-module-command-kubouch).
Everything else is just whitespace and improved test reliability. The tests pass on v0.75.0 and earlier (not just v0.75.0).
> fix: support nushell v0.75.0

- completions/asdf.bash
Adds _latest_ to the list of commands available for bash tab completion.
Fixes: #1440 
N/A
> fix: bash completion for latest command

- asdf.nu
Nushell, at least in recent versions (I did not check ancient versions) needs to have the `$PATH` variable split on the separator character (`;` for Windows, otherwise `:`). Currently, asdf is broken with Nushell as a result.
Fixes: #1458 
None
> fix: nushell PATH conversion to list before filter

- docs/guide/getting-started.md
I saw that there was no "Dependency Installation" for Enterprise Linux.
> docs: list asdf-nodejs deps for enterprise linux in guide

- asdf.nu
In the Nushell setup script, I change the paths to asdf shims and bin to be prepended in front of the existing `$PATH` instead of being appended at the end. This change makes asdf plugins have priority over the existing commands in the search path as well as other shells' setup.
> fix: Prepend asdf directories to the PATH in Nushell

- .github/workflows/tests.yml
- Elvish versions listed here: https://dl.elv.sh/linux-amd64/
- Nushell versions listed here: https://github.com/nushell/nushell/releases
Since these are both pre `1.0.0` release we should try to keep up to date with testing against the latest.
> ci: bump nushell & elvish versions

- asdf.sh
- docs/guide/getting-started.md
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
- lib/asdf.sh
- scripts/format.bash
- scripts/shellcheck.bash
- scripts/shfmt.bash
Earlier it was discovered that `shfmt` and `shellcheck` were not running properly on some entrypoint files (`asdf.sh` and `lib/asdf.sh`. As #1397 states, they were identified as Bash when they should have been identified as POSIX shell.
This PR updates both shfmt and shellcheck to parse the aforementioned files as `POSIX` with one slight nuance:
- `shfmt` sometimes spuriously prints errors when encountering ZSH-specific syntax (`./asdf.sh:34:16: parameter expansion requires a literal`). Because of this, `shfmt` no longer runs on `asdf.sh`.
I'm not sure if there is still confusion as to whether these files should be treated as (Bash and ZSH) or POSIX, but because we know (from #1138) that users are using shells such as `mksh` (and at least for me, I know I want `asdf` to continue to work …
> fix!: rework POSIX entrypoint for greater shell support

- asdf.nu
- test/asdf_nu.bats
> fix: nushell plugin list all (#1501)

- docs/guide/getting-started.md
Fix the problem that ASDF_NU_DIR does not fight for an invisible newline character at the end of the brew --prefix command
> docs: fix Nushell-Homebrew setup instructions

- asdf.nu
- lib/functions/plugins.bash
- lib/utils.bash
- test/asdf_nu.bats
Fixes: #1503.
Also adds tests for the `--refs`flag and its combination with `--urls`.
Note that installed plugins can have a "remote" URL of two forms:
- a remote git URL (i.e. starting with `http[s]|git` and terminating with `.git`)
- an absolute path to a local folder
**N.B.**: At the moment this PR is only testing for plugins added from a local folder (second case above). To test plugins that have been cloned from an *actually remote* repository (first case above) there have to be testing fixtures that clone them first.
> fix: Nushell plugin list --urls

- bin/asdf
- lib/commands/command-plugin-remove.bash
- lib/utils.bash
- test/reshim_command.bats
- test/shim_exec.bats
- test/test_helpers.bash
I saw that there was a `ASDF_BATS_SPACE_IN_PATH` variable, which seemed to be part of a gradual transition to make the tests work better with whitespace stuff. Probably with help from #1433, it was somewhat trivial to make the proper fixes and remove this variable entirely.
One test was left out because it seems that change requires a fix in the `.tool-versions` parser (related to the `path:~/src/elixir` feature)
> fix: Better handling with paths that include spaces

- docs/manage/configuration.md
Improves wording of environmental variables section in two ways:
1. No longer refer to `~/.asdf` as an absolute path
Beginners may take this too literally and do something like `export ASDF_DATA_DIR=~/.asdf`, which won't work since tilda expansion doesn't occur here (since the `~/` isn't the first two characters in the word, the `AS` in `ASDF_DATA_DIR` is).
To prevent misconceptions or potential issues, this has been removed.
2. Update description of `ASDF_DIR`
This variable no longer defaults to `~/.asdf`, but instead is [dynamically set](https://github.com/asdf-vm/asdf/blob/05a8bb940a9ce1a83dcda2a2bf52dc3d0786bd54/lib/utils.bash#L27) and always refers to the true location of the source files.
> docs: Improve wording of env vars section

- lib/commands/command-info.bash
- test/info_command.bats
These changes make two fixes with the `info` subcommand:
- Use `$BASH_VERSION` for info about the current version of Bash because:
- `$SHELL --version` is too verbose
- `$SHELL` breaks when Bash is installed in a location that contains spaces (ShellCheck misses this because it seems it hard-codes `SHELL` as an exception)
- `$SHELL` breaks when a login shell other than Bash is used
- Change printing of environment variables so that
- All variables that asdf uses are printed, even if they are not set
- Remove exec/subshell
<details>
<summary>Sample Output</summary>
```
$ asdf info
OS:
Linux nullptr 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
SHELL:
Bash 5.1.16(1)-release
ASDF VERSION:
v0.11.3-f5f391c
ASDF ENVIRONMENT VARIABLES: …
```
> fix: `asdf info` show BASH_VERSION & all asdf envs

- bin/asdf
- scripts/checkstyle.py
I noticed that `bin/asdf` wasn't added to the checkstyle script. This does that, runs `checkstyle --fix`, and makes miscellaneous changes to the types and comments in the checkstyle script.
> fix: lint & style errors in `bin/asdf`

- test/asdf_elvish.bats
- test/asdf_fish.bats
- test/asdf_nu.bats
Before:
```sh
- exports ASDF_DIR (skipped: Elvish version is not at least 0.18. Found ..)
```
After:
```sh
- exports ASDF_DIR (skipped: Elvish not installed)
```
This also makes sure that CI fails if a particular shell isn't installed.
> test: skip tests for uninstalled shells when run locally

- bin/asdf
- lib/functions/versions.bash
- lib/utils.bash
As mentioned [here](https://github.com/asdf-vm/asdf/pull/1513#discussion_r1147979242), this fixes the behavior of defaulting `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME` to the correct version. This is also done to `$ASDF_DATA_DIR`.
> fix: assign default values to all internal variables

- asdf.sh
The PATH issue was briefly mentioned in the original [POSIX entrypoint PR](https://github.com/asdf-vm/asdf/pull/1480#issue-1590511816), but it was not fixed there.
The issue is that previously `asdf` modified the PATH variable, and removed the asdf bin or asdf shims directory (from PATH) if they existed. Besides not being good practice (in my opinion), this had issues since this behavior would only run under Bash and ZSH (POSIX doesn't support substitution in parameter expansion and I intentionally didn't add this behavior to KSH for simplicity). Since the same script could change PATH differently (when ran under different shells), this can be confusing behavior. Also, neither the Elvish, or Nushell scripts remove items from the PATH, this also could be confusing.
These changes make it so …
> fix!: do not remove items from PATH in POSIX entrypoint

- docs/manage/versions.md
Changing `ASDF_${LANG}_VERSION` to `ASDF_${TOOL}_VERSION` for consistency.
`ASDF_${TOOL}_VERSION` is used pretty consistently in this page, and I initially thought `ASDF_${LANG}_VERSION` was something different. Updating for consistency.
> docs: fix `ASDF_${LANG}_VERSION` usage

- .github/workflows/tests.yml
```diff
-  NUSHELL_VERSION: 0.77.0
+  NUSHELL_VERSION: 0.78.0
```
> chore: bump nushell version in CI

- .github/workflows/tests.yml
Currently we pin Shell versions for Elvish & Nushell. We do not for Fish or Powershell.
We should be consistent. So this PR introduces pinning to Fish & Powershell.
Homebrew installation on the macOS runner wasn't using any pinned versions. We will leave this as is for now.
> ci: pin all shell versions for Ubuntu test environment

- lib/commands/reshim.bash
- lib/functions/installs.bash
- scripts/checkstyle.py
Make redirections more consistent
> fix: enforce consistent shell redirection format

- test/latest_command.bats
- test/list_command.bats
- test/plugin_test_command.bats
- test/shim_exec.bats
- test/uninstall_command.bats
- test/update_command.bats
- test/utils.bats
Sorry for all the PRs, here is another that fixes useless `echo -e`s and extraneous `echo`s
> test: rm useless `echo` usage in tests

- scripts/format.bash
This updates the `scripts/format.bash` script to no longer try and format files removed in #1525
> chore: rm format script config for removed files

- completions/asdf.fish
Fixes: #1542
The recommended fix was good, but this uses only builtins
> fix: remove leading asterick in Fish completion

- bin/asdf
- lib/functions/versions.bash
- lib/utils.bash
Applied suggestions from [here](https://github.com/asdf-vm/asdf/pull/1485#discussion_r1164088836) and [here](https://github.com/asdf-vm/asdf/pull/1518#discussion_r1159820722).
> fix: rename internal function `asdf_tool_versions_filename`

- docs/manage/core.md
- docs/pt-br/manage/core.md
- docs/zh-hans/manage/core.md
Fix uninstall instructions for Fish Shell.
The syntax used is not supported in Fish Shell https://stackoverflow.com/questions/75492179/how-to-convert-export-line-from-bash-to-fishvariable-expansion-shortcuts. I'm not sure if the new version is the most correct, but it at least works.
> docs: fix uninstall instructions for Fish Shell

- defaults
- docs/manage/configuration.md
- lib/functions/installs.bash
- test/install_command.bats
Fixes #1097
Use by either setting:
- environment variable `ASDF_CURRENCY`
- config key `concurrency`
> feat: Support configurable `ASDF_CONCURRENCY`

- .github/workflows/release.yml
Use custom release-please PR section titles.
- Currently all `fix:` commits are categorized under "Bug Fixes". With our use of [Convention Commits](https://www.conventionalcommits.org/en/v1.0.0/), `fix:` actually covers all changes which require a Patch version update. So we should just call that changelog section "Patches".
- track documentation changes in the Changelog as well (I have found our previous changelogs which tracked this information to be helpful when identifying when behaviour was added and if there was accompanying docs from separate PRs).
I expect this change to result in PR & Changelog sections as:
```diff
BREAKING CHANGES
Features
-Bug Fixes
+Patches
+Documentation
```
* I am unsure if this configuration affects the "BREAKING CHANGES" section. I assume not.
* This will …
> ci: custom release PR sections & titles

- lib/utils.bash
- test/utils.bats
Title. It was recommended in the linked issue to exit the program as well, but that was not attempted because there are various instances where the code could be ran in subshells (in which case, only the subshell will be exited).
Fixes #1476
> fix: Print warning if `.tool-versions` or asdfrc contains carriage returns

- bin/asdf
Looking at [CI runs](https://github.com/asdf-vm/asdf/actions/runs/5130651562/jobs/9229710004?pr=1566), it looks like the lack of these directives is causing linting to fail. ~~This suggests that on newer versions, ShellCheck bumped errors like [SC1091](https://www.shellcheck.net/wiki/SC1091) from info to error.~~
> fix: Add ShellCheck directives to find sourced files

- asdf.sh
- docs/guide/getting-started.md
- docs/manage/configuration.md
This variable forces the prepending of the asdf directories to the PATH variable. It does this by removing existing asdf entries in PATH, including an optimization for Bash and Zsh shells.
Fixes #1550
> fix: Introduce `ASDF_FORCE_PREPEND` variable on POSIX entrypoint

- asdf.fish
In the fish entry point, only make the ASDF_DIR path absolute, and don't resolve symlinks.
Without this change, a `brew upgrade` causes all the shims to be broken.
When asdf is installed by homebrew, it is placed in a versioned directory and then symlinked to `/usr/local/opt/asdf`. If the symlink is resolved, ASDF_DIR contains the versioned directory. This is a problem because shims use the value of ASDF_DIR to get an absolute path to the asdf executable.
Not resolving symlinks is in line with the `asdf.sh` entry point.
> fix(fish)!: don't resolve symlinks for ASDF_DIR

- lib/functions/plugins.bash
- test/plugin_add_command.bats
Closes #841 
I do not consider this a breaking change because the fixed behavior does not break currently existing scripts that have the workaround (ie `(exit 2) || :` has the same affect as `(exit 0) || :`)
> fix!: exit success when adding an already-added plugin

- lib/functions/plugins.bash
Closes #903
I do not consider this a breaking change because the fixed behavior falls into line with existing package managers. If one needs to test if no packages are installed, the better option is to parse standard output.
> fix!: `plugin list` exit code 0 when no plugins are installed

- scripts/install_dependencies.bash
- scripts/lint.bash
- scripts/test.bash
- Makes prints semantically dry
- Use physical directory when comparing to see if script is running in `asdf` repository. (Unfortunately `set -o physical` does not work with `$PWD`)
- Other small fixes
> fix: improve lint and test scripts

- bin/asdf
There have been several cases in which users have mistakenly marked files under `./lib/commands/` as executable. This creates mysterious errors as seen in the linked issue.
To prevent this and reduce frustration, show an error message so users can more easily diagnose the issue without looking at the source code.
Closes #1540
Closes #1596 (local setup issue, not asdf)
Closes #1478 (resolved)
> fix: Show warning when any ./lib/commands are marked as executable

- asdf.sh
Add default values for `BASH_VERSION`, `ZSH_VERSION`, `KSH_VERSION`.
Shell which sets option `nounset` occurs following error.
```bash
$ /opt/homebrew/opt/asdf/libexec/asdf.sh:68: BASH_VERSION: parameter not set
```
> fix: Set default shell version values on POSIX entrypoint

- .github/dependabot.yml
This will group Dependabot updates for all changes to the `docs/` `npm` dependencies into a single PR per month.
> ci: use dependabot groups for `docs/` dependency PRs

- asdf.nu
- docs/guide/getting-started.md
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
- scripts/install_dependencies.bash
- test/asdf_nu.bats
Nushell integration is broken because of the deprecated `let-env`, see https://www.nushell.sh/commands/docs/let-env.html#frontmatter-title-for-removed for details.
Fixes: #1609 
There is already pull request #1610 that does not seem to be worked on at the moment.
Manual testing on my MacBook M1 worked. I tried running the automated test suite, but there were too many unrelated errors. I hope your CI will tell us whether I did everything right.
Linting worked.
> fix: nushell language syntax update

- asdf.fish
Fixes the issue raised in a PR comment here: https://github.com/asdf-vm/asdf/pull/1583#issuecomment-1714212545
Fish treats their `realpath` builtin as a fallback in case a system version doesn't exist. Not all versions of `realpath` support the `--no-symlinks` flag, which `asdf.fish` uses. This PR ensures that the builtin version of `realpath` is always used.
Just as a note for posterity, the `--no-symlinks` flag for the builtin `realpath` was added in fish 3.2.0, released in March 1, 2021. 2 years old is good, but some slower Linux distros may lack support. If that proves to be a problem, then perhaps a different solution can be found. I think long term though the builtin will offer the best support across different systems.
> fix(fish): use builtin realpath over system one

- .github/workflows/semantic-pr.yml
GitHub now supports, and we use, the setting which sets the squash commit message the PR title.
Since this is now the case, we no longer require single-commit-PRs to have those single commits match the Semantic PR settings.
This will mean the errors from Semantic PR only apply to PR titles and are therefore easier to fix than the single-commit commit message.
I noticed this unnecessarily tripping some people up across the repos.
> ci: remove semantic release single-commit rule

- bin/asdf
This is a bug.
Closes #726
Closes #1365 (duplicate)
Closes #729 (duplicate, solved, stale)
> fix: plugin extension commands to not require `bin/` directory

- docs/guide/getting-started.md
Just a minimal visual correction in the documentation.
> docs: Remove superflous characters

- docs/manage/configuration.md
- docs/plugins/create.md
- docs/zh-hans/plugins/create.md
- Document plugin hooks in `.asdfrc` section
- Fix typo when referencing [{pre,post}_asdf_plugin_update](https://github.com/asdf-vm/asdf/blob/4085e5542bac824ea124610ad247c2f90d1b8d93/lib/functions/plugins.bash#L164) hooks
Closes #1529
Closes #1466
> docs: Improve `.asdfrc` plugin hook docuentation

- scripts/install_dependencies.bash
Recently, there have been errors in CI as packages from the Fish PPA (https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) have been removed.
Unfortunately, it seems that `3.6` is no longer installable so the version was bumped
> ci: Update Fish dependencies

- asdf.nu
- docs/guide/getting-started.md
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
- test/asdf_nu.bats
It was [a mistake](https://github.com/asdf-vm/asdf/pull/1624#discussion_r1319269045) to read the `ASDF_NU_DIR` environment variable (it looks like use of it snuck through the CR). Since it serves the exact same purpose as `ASDF_DIR`, it is redundant. Remove mention of this variable, but keep reading it for backwards-compatability.
Closes #1623
Closes #1630
> fix: Avoid mention of `ASDF_NU_DIR`

- lib/commands/command-plugin-test.bash
- lib/commands/reshim.bash
- lib/functions/versions.bash
`--quiet` is an improvement over `>/dev/null` when checking the exit code to check for a string's existence. Using the former better ensures grep does not return an exit code that is unrelated to condition that a substring or regex is contained within a target string (which is the actual semantics of these particular command executions).
- Closes #1584 (personal configuration issue)
- Closes #1651 should be moved to `asdf-python`
> refactor: Prefer grep's `--quiet` over standard output redirection

- docs/plugins/create.md
- docs/pt-br/plugins/create.md
- docs/zh-hans/plugins/create.md
- lib/commands/command-plugin-test.bash
It implements the strategy followed by #800 to retrieve the plugin's default branch instead of relying on master.
Fixes: #974
> fix: `plugin test` git-ref default to the default branch of the plugin's repository

- help.txt
Adds a line for the "asdf version" command which was missing from the "UTILS" section of help.txt
> feat: Adds "asdf version" under the "UTILS" section of help.txt

- asdf.fish
This PR addresses issue described in #1629. Currently the Fish shell setup script sets fish_user_paths as a global variable.  This conflicts with the expected universal nature of fish_user_paths, leading to path assignments not persisting across sessions when using fish_add_path.
Fixes:
- fish-shell/fish-shell#9819
- #1629
This ensures that any paths added via fish_add_path are retained across all Fish shell sessions, aligning with the standard behavior of fish_add_path as outlined in its [documentation](https://fishshell.com/docs/current/tutorial.html).
> fix: use universal scope for fish_user_paths in fish shell integration

- asdf.fish
Update `asdf.fish` to modify `$PATH` directly, rather than using `$fish_user_paths`. This respects the user's choice between a universal or global `$fish_user_paths`, addressing an issue where the previous `asdf.fish` made this decision on behalf of the user.
Modifying `$PATH` directly was recommended by @faho (long time Fish shell contributor) and avoids assumptions about `$fish_user_paths` being global or universal, which should be the shell users decision. Note that in fish `$PATH` cannot be a universal variable (it's simply inherited from the parent process), so it does not have this issue.
This approach also aligns with initialisation scripts from other projects, such as those from [brew](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.sh#L35) and …
> fix: use PATH instead of fish_user_paths + tests

- lib/functions/installs.bash
- test/install_command.bats
Currently, the warning which is intended to alert users that the download directory can't be kept only appears if they haven't asked for it to be. This fix just rearranges the logic a bit so that the warning instead only appears if the download directory *should* be kept, but *can't* be (because it doesn't exist).
Fixes: #1711
> fix: Only display the "can't keep downloads" warning when asked to keep downloads

- lib/commands/command-plugin-test.bash
the alpine (busbox) version of `mktemp` expects templates to end with exactly 6 Xs whereas GNU want at least 3.
Bumping to 6 Xs allows alpine users to run the plugin-test command without installing the `coreutils` package first
On alpine anything with less than 6 Xs is an error
On ubuntu it doesn't matter if its 4 or 6
It will also fix running the `asdf-vm/actions/plugin-test` actions on an alpine container (for now an `apk add coreutils` is required)
> fix: make plugin-test work on alpine linux

- lib/commands/command-update.bash
- scripts/install_dependencies.bash
- test/asdf_elvish.bats
- test/asdf_nu.bats
- test/update_command.bats
The Go version of asdf in PR #1805 cannot be upgraded to
with `asdf update` so the command has been replaced with
a message instructing users to Go to the asdf website or
use their OS package manager to install the latest
version of asdf.
Related to https://github.com/asdf-vm/asdf/pull/1805
Also fix failing build by:
* Correcting dependencies on Ubuntu GitHub workflow runners
* Fixing elvish shell test
* Commenting out failing nushell tests
> feat(golang-rewrite): remove `asdf update` command to prepare for Go version

- docs/guide/getting-started.md
This was fixed over a year ago in oh-my-zsh commit 278bcfc
https://github.com/ohmyzsh/ohmyzsh/commit/278bcfc
> docs: Remove warning about oh-my-zsh-plugin

- internal/cli/set/set_test.go
- internal/toolversions/toolversions.go
Ensures that there is only a single trailing new line in the `.tool-versions` file.
Fixes #1840
> fix(golang-rewrite): Fix new lines from `asdf set` command

- .editorconfig
line ending for shell scripts should be LF
Fixes: #1846, #1799
> fix: bash command set end of line LF

- docs/guide/upgrading-from-v0-15-to-v0-16.md
- docs/plugins/create.md
- internal/plugins/plugins.go
- internal/plugins/plugins_test.go
* Remove incorrect breaking change from docs
* Handle missing post-plugin-update callback
> fix(golang-rewrite): allow missing post-plugin-update callback during plugin update

- internal/cli/cli.go
The Homebrew tests expect this.
> fix(golang-rewrite): plugin list print messsage to stderr when no plugins installed

- docs/.vitepress/sidebars.ts
- docs/guide/getting-started-legacy.md
- docs/guide/getting-started.md
- docs/guide/upgrading-to-v0-16.md
- docs/manage/configuration.md
- docs/manage/versions.md
- docs/parts/install-dependencies.md
- docs/plugins/create.md
- internal/completions/asdf.zsh
This should be merged right before #1814 is merged.
* Add sidebar link for 0.16.0 upgrade guide
* Rename 0.16.0 upgrade guide page
* Add legacy getting started guide
* Update installation instructions
* Update Bash, Fish, Zsh, Nushell, and POSIX configuration instructions
* Remove warning about oh-my-zsh issue
> chore(docs): update documentation for asdf 0.16.0

- bin/asdf
Message is printed to STDERR to try to minimize its impact on existing systems.
In preparation for the upcoming release of the Go code. Should only be merged along with #1826
> feat(golang-rewrite): add 0.16.0 migration notice to old Bash code

- docs/guide/getting-started.md
Advertised go install command does not work...
~~~
> go install github.com/asdf-vm/asdf@v0.16.0
package github.com/asdf-vm/asdf: build constraints exclude all Go files in /home/isi/.cache/go/pkg/mod/github.com/asdf-vm/asdf@v0.16.0
~~~
because entrypoint is under `cmd/asdf`. This works:
~~~
> go install github.com/asdf-vm/asdf/cmd/asdf@v0.16.0
go: downloading github.com/sethvargo/go-envconfig v1.0.0
go: downloading github.com/go-git/go-git/v5 v5.13.0
go: downloading github.com/urfave/cli/v2 v2.27.1
go: downloading dario.cat/mergo v1.0.0
go: downloading github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376
go: downloading github.com/pjbgf/sha1cd v0.3.0
go: downloading github.com/ProtonMail/go-crypto v1.1.3
go: downloading github.com/go-git/go-billy/v5 v5.6.0
go: downloading …
> docs: Fix go install command in getting-started.md

- docs/guide/getting-started.md
The ZSH Configuration section was saying to add path in bashprofile file instead of zshrc
> docs: update path from `~/.bashprofile` -> `~/.zshrc` for zsh

- internal/execenv/execenv.go
- internal/execenv/execenv_test.go
The old code did not allow the equals sign in the environment variable value. But the equals sign is a valid character in value.
Fixes https://github.com/asdf-vm/asdf/issues/1876
> fix: correct SliceToMap environment variable parsing function

- internal/resolve/resolve.go
- internal/resolve/resolve_test.go
- internal/shims/shims.go
- internal/versions/testdata/asdfrc
- internal/versions/versions_test.go
* Use version in home dir when no version found in root dir
* Correct `FindExecutable` function so returns `NoVersionSetError` even when `.tool-version` file located
* Update `resolve` and `versions` package tests to use test plugin name
Fixes #1860
> fix: use version in home dir when no version found in root dir

- internal/completions/asdf.bash
Rewrite of the completion bash removing the hyphenated commands and adapting the other changes in command line.
Fixes: #1867
> fix: completion bash

- docs/guide/upgrading-to-v0-16.md
Nothing major, only two simple typos with $PATH missing the ending `
> docs: corrected highlighting for PATH

- go.mod
- go.sum
Used version of urfave/cli v2.27.1 prints
extra line into output for every command executed. e.g. go mod tidy would result output have initial line App.Run asdf, exec, go, mod, tidy
This behaviour breaks most cli tools which depend on other tools output e.g. json output. Update to v2.27.5 fixes this issue.
> fix: update urfave/cli to fix cmd output

- internal/completions/asdf.bash
Update the completion bash with the fix from 554b4ea
> fix: correct help for asdf set command completion bash

- docs/guide/upgrading-to-v0-16.md
This PR fixes typos in the [Upgrading Without Losing Data](https://asdf-vm.com/guide/upgrading-to-v0-16#_1-download-the-appropriate-asdf-binary-for-your-operating-system-architecture) section of the `Upgrading to 0.16.0` documentation. The existing typos caused errors when copying and pasting the provided commands, which this update resolves.
> fix: correct typo in `Upgrading to 0.16.0` documentation

- internal/completions/asdf.fish
Fixes related to #1934 & #1908
Earlier changes introduced in #1912 broke the fish shell completions. The changes were for both `zsh` and `fish`. Though, here we are making changes only for fixing `fish`.
There is room for improvement but the fix right now is focused to make the broken stuff work. 
Below commands are removed
- `global`
- `local`
- `update`
> fix: repair invalid fish shell completion code

- docs/guide/getting-started.md
This pull request fixes a minor typo in the asdf configuration documentation. The documentation originally stated:
> if $HOME/.asdf isn't the directory you want asdf writing **too**, you can change it.
It has been updated to:
> if $HOME/.asdf isn't the directory you want asdf writing **to**, you can change it.
Fixes: [asdf-vm/asdf#1942](https://github.com/asdf-vm/asdf/issues/1942)
There are no additional changes beyond the documentation fix. Thank you for reviewing this contribution, and thank you for maintaining asdf!
> docs: correct typo in asdf configuration guide

- docs/guide/upgrading-to-v0-16.md
Based on the description I believe the `asdf cmd foo bat man` has a typo in the name of the command thats bring run.
This PR changes the example
> docs: fix command examples in upgrading-to-v0-16 guide

- internal/cli/cli.go
- internal/shims/shims.go
- internal/shims/shims_test.go
- test/reshim_command.bats
Fixes https://github.com/asdf-vm/asdf/issues/1891
Also update `asdf reshim` so it prints an error when plugin with name is not found.
> fix: return no error from shims.RemoveAll when shims dir missing

- internal/execenv/execenv.go
- internal/execenv/execenv_test.go
- internal/execute/execute.go
- internal/execute/execute_test.go
Simplifies the parsing of env vars reported by bash by parsing NULL delimited values rather than new lines.
Fixes: https://github.com/asdf-vm/asdf/issues/1986
> fix: simplify env vars parsing

- cmd/asdf/main_test.go
- internal/cli/cli.go
- test/non_existent_command.bats
Change exit status code when command does not exists.
Fixes #1928
> fix: correct exit status when sub-command does not exist

- .editorconfig
- .gitignore
- internal/cli/cli.go
- internal/help/help.go
- test/plugin_extension_command.bats
Addresses the feedback mentioned here: https://github.com/asdf-vm/asdf/pull/1982#issuecomment-2682248660
The solution outlined here strips values which should not be passed through asdf on recursive calls. It's done before any other logic is invoked in order to minimize the number of places that need to consider this case. Open to feedback on this approach.
> fix: set correct env vars on recursive calls

- test/plugin_extension_command.bats
Check for existence of environment variables with `ASDF_INSTALL_` prefix rather than `ASDF_INSTALL_` in the value of the variables.
Fixes: 2005
`bats` is setting a variable with the description of the test running causing the test to fail:
```
BATS_TEST_DESCRIPTION=asdf execute plugin default command unsets ASDF_INSTALL_TYPE ASDF_INSTALL_VERSION and ASDF_INSTALL_PATH env variables
```
Related to: https://github.com/asdf-vm/asdf/pull/1982
> fix: correct ASDF_INSTALL_* envvar unset test

- internal/versions/versions.go
- internal/versions/versions_test.go
PR based on feedback in https://github.com/asdf-vm/asdf/pull/2008 . This PR will remove the install directory for the given version if it fails to install (install command returns a non-zero exit code).
Fixes: https://github.com/asdf-vm/asdf/issues/1981
Fixes: https://github.com/asdf-vm/asdf/issues/1940
> fix: remove install directory for version when install fails

- docs/guide/getting-started.md
asdf is now available in openSUSE through Zypper! I just added it to the official documentation.
> docs: add Zypper to the package managers in which asdf is available

- internal/completions/asdf.zsh
The first line of a completion file must be `#compdef`, removed the comment that was added above it.
Fixes: #2035
> fix: remove comment from first line zsh completion output (#2035)

- docs/guide/upgrading-to-v0-16.md
This pull request addresses an issue in the guide where users are instructed to download the binary, but no direct link is provided. This omission has caused confusion. With this change, a direct link to the binary is added to enhance clarity and user experience.
> chore(docs): add binary download link to guide page

- internal/installs/installs.go
- internal/installtest/installtest.go
- internal/shims/shims.go
- internal/shims/shims_test.go
- internal/toolversions/toolversions.go
- internal/toolversions/toolversions_test.go
I commonly make use of `ref:` based installs when working in `erlang` and `elixir` repositories, however this appears to be broken in the current builds as the `ref:` prefix is normalized to `ref-` when working with file path rendering the ref based installs unlocatable by the shim.
Fixes: #2001
I do not know if there is a better place to do this, I am happy to make the changes in the correct area if you feel it is needed.
> fix: support ref installed tool shims

- internal/shims/shims.go
- internal/shims/shims_test.go
- internal/toolversions/toolversions_test.go
* add more tests for `toolversions.Intersect` function
* add failing test for `shims.FindExecutable` function
* correct intersection logic in `shims.FindExecutable` function
Fixes https://github.com/asdf-vm/asdf/issues/2038
> fix: correct intersection logic in `shims.FindExecutable` function so ordering of multiple versions is preserved

- .release-please-manifest.json
- Makefile
- cmd/asdf/main.go
- test/help_command.bats
- test/non_existent_command.bats
Intended to address https://github.com/asdf-vm/asdf/issues/2046 and related issues.
With these changes the version will always look something like this:
```
$ ./asdf version
0.16.7 (revision 610d084)
```
> fix: set correct version for go install and make builds

- internal/repotest/repotest.go
I noticed that while running tests, a dialog asking for my GPG key password was popping up. This is because I sign all my commits, and because repotests is using the `git` command behind the scenes using my global `~/.gitconfig`.
In this PR I'm setting the 
Fixes: List issue numbers here `GIT_CONFIG_GLOBAL` variable to `/dev/null` for all commands run on repotest, so it ignores the [global user config](https://github.com/git/git/commit/4179b4897f2de28858acaebd6382c06c91532e98), which to me seems logical, since we are using git just for a simple test.
> test(golang-rewrite): ignore global git config on repotest

- internal/cli/set/set.go
- internal/cli/set/set_test.go
Fixes https://github.com/asdf-vm/asdf/issues/2095
This PR corrects code submitted in https://github.com/asdf-vm/asdf/pull/2096
> fix: ensures output always ends with a newline when printed

- internal/versions/versions.go
- internal/versions/versions_test.go
Fixes: https://github.com/asdf-vm/asdf/issues/2073
Previously the code for the latest command would always filter out versions not starting with a number, even when the user provided a filter of their own that specifically looked for a non-numeric version.
> fix: only return version starting with number when no filter is supplied

- asdf.nu
- docs/pt-br/index.md
- docs/zh-hans/manage/versions.md
- internal/cli/cli.go
- internal/completions/asdf.nushell
- test/utils.bats
Fix typos found via `codespell -S pt-br -L devlop` and `typos --hidden --format brief`
None.
> docs: fix typos again
