asdf-vm/asdf

- README.md
I wrote some plugins for openresty, postgres, redis, and riak and added them to the list.
> Updated README.md to include new plugins

- README.md
- asdf.fish
- completions/asdf.fish
I added support for [fish shell](http://fishshell.com/), with nice completions :tada:
> Add fish support.

- README.md
- bin/asdf
- completions/asdf.fish
- help.txt
- lib/commands/version_commands.sh
- lib/utils.sh
- test/utils.bats
- test/version_commands.bats
I implemented what I talked to you about on Twitter.
https://twitter.com/tuvistavie/status/722089523916591104
I borrowed the `global` and `local` from rbenv/pyenv, but if you have any better suggestion
for the command names I am of course completely open.
> Add support for local and global commands.

- docs/creating-plugins.md
- lib/utils.sh
@Stratus3D @tuvistavie I've made the required change to read option from config. If you guys can verify this once, I'll go ahead and merge this.
> Check if legacy version file support is enabled before using it

- bin/asdf
- docs/creating-plugins.md
- lib/commands/plugin-add.sh
- lib/commands/plugin-test.sh
@HashNuke I believe this will help keeping good quality plugins.
It helped me find out my Python plugin did not work on OSX :sweat: 
I would also like to merge #48 so it will help to check if everything works.
> Add command and instructions to test plugin.

- docs/creating-plugins.md
- lib/commands/plugin-test.sh
My Python plugin [should never have passed the tests](https://github.com/tuvistavie/asdf-python/pull/1/files) but it did, so I improved the `plugin-test` command a little.
> Improve plugin tests

- asdf.sh
- completions/_asdf
> zsh: remove _asdf completion.

- lib/commands/plugin-add.sh
- lib/commands/plugin-update.sh
This improves some of the error messages when calling plugin-add and plugin-update with the wrong amount of arguments.
> Argument validation

- README.md
- help.txt
- lib/commands/version_commands.sh
- test/test_helpers.bash
- test/version_commands.bats
This makes `asdf local` and `asdf global` setters only. `asdf current` will be the command to get the current version.
> Unify Version Getter

- README.md
I noticed we didn't have the .asdfrc file documented anywhere so I figured I would add a section to the readme.
> Add section to readme on the .asdfrc file.

- lib/commands/version_commands.sh
- test/version_commands.bats
This should fix #89. This is my first time writing bats tests and also my first time working with the code for the local/global setters, so I'd like someone look this over and provide some feedback. 
- Are there other things I should test? 
- Are there other places in the code that might contain similar bugs?
> Local whitespace fix

- README.md
Working through the asdf install and noticed. Cheers
> "You" to "Your" in README

- lib/commands/install.sh
- test/install_command.bats
Also added a test for this issue so I could verify that it was in fact broken.
> More whitespace fixes

- README.md
Plugin for installing [LFE](https://github.com/rvirding/lfe)
> Add asdf-lfe

- README.md
Created a plugin using the Rust project's rustup.sh script.  Should fix #36.
> Added Rust plugin to README

- README.md
[vic/asdf-elm](http://github.com/vic/asdf-elm) plugin for [Elm](http://elm-lang.org)
> Add asdf-elm plugin.

- README.md
[plugin](http://github.com/vic/asdf-idris) for installing [Idris](http://idris-lang.org)
> Add Idris plugin

- test/fixtures/dummy_plugin/bin/install
- test/install_command.bats
Test using a dummy executable.
Closes #127
> Test produced shims by actually running them.

- README.md
Updates: Synced the repository from #48, and removed Scala plugin.
(Scala plugin from #126 seems to handle version updates automatically, which I haven't been able to do)
> Add D(DMD) plugin

- README.md
- lib/commands/reshim.sh
Adding Scala plugin on another branch.
> Add Scala Plugin

- lib/commands/reshim.sh
Broken here:
https://github.com/asdf-vm/asdf/commit/00bf082b316850e3975072e42a85d847dcc82200#diff-774f80a035a812fafdd48ebc7c8b6af4R54
but this time we have tests to notice:
https://travis-ci.org/asdf-vm/asdf/builds/184202823
> Fix shim args again.

- test/utils.bats
Thanks for the additional tests @vic. Since tests currently take only 13 seconds I don't see any reason why we shouldn't add a few more.
> Add couple of tests

- README.md
Add my asdf-sbt link in the README file.
> add sbt plugin in readme

- lib/commands/plugin-add.sh
The next step in addressing #124. We should not alter plugin files at all.
> Don't change the permissions on files in a plugin's bin directory.

- asdf.sh
> Properly address shellcheck warnings ignored in #156

- bin/asdf
- completions/asdf.bash
- help.txt
- lib/commands/update.sh
- test/update_command.bats
I finally fixed the failing tests for this feature. There was one assertion that I was unable to fix, and I was unable to replicate the failure of it on OSX, Ubuntu 16.04, and CentOS 7 so I commented it out in the test.
This should complete #172. Rejected #177 #179 due to many tests failing on Travis CI.
> Asdf update command with tests

- CHANGELOG.md
- README.md
I figured we'd go ahead and do another minor release since we've changed how we install plugins (no more chmod'ing of the files in the bin/ directory). Though perhaps I should have just made this a patch release...
I'll tag as soon as this is merged.
> Add items to changelog in preparation for 0.3.0 release.

- ballad-of-asdf.md
This adds line breaks to restore the ballad to its original glorious formatting.
> Fix ballad formatting

- bin/asdf
- completions/asdf.bash
- help.txt
- lib/commands/which.sh
- test/which_command.bats
Hi guys, this is my attempt to do the which command it fixes #72 and #150.
I guess it could be better when returning the main binary, but I think would need a Plugin API change.
Hope it helps!
> Which command

- README.md
To match other command examples.
> Comment out 'set current version' example in readme

- README.md
Yep, I'm back again. Honest, I just messed with a lot of stuff today and I needed a few things easily installable...
> adding asdf-gradle

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Added a few files which should hopefully improve the quality of issues and PRs we receive.
> Add contributing guidelines

- .gitignore
- bin/asdf
- lib/commands/plugin-list-all.sh
- lib/utils.sh
- test/fixtures/dummy_plugins_repo/plugins/bar
- test/fixtures/dummy_plugins_repo/plugins/foo
- test/plugin_list_all_command.sh
- test/test_helpers.bash
`asdf plugin-list-all` will show a list of all the available commands in the plugin repository.
> Add plugin-list-all command

- CONTRIBUTING.md
Fix creating-plugins link in CONTRIBUTING.md.
> Fix creating-plugins link

- README.md
Update install instructions on the Readme to make it easier to understand :heart:
> ![image](https://user-images.githubusercontent.com/74385/31932536-1da9b09e-b8d9-11e7-805e-97527b27c2d5.png)
I'd like to propose adding Fish + Fisherman integration via https://github.com/rstacruz/fish-asdf — but I figured it'd be best to clean this part up before adding more variants in.
> Readme: format install instructions better

- README.md
- help.txt
Add `asdf current` to README and `asdf -h`
PS. sorry about the markdown formatting, [Prettier](https://prettier.io/) ran on save
Fixes: Closes #257
> Add `asdf current` to README and `asdf -h`

- lib/commands/current.sh
Print "No version set" message to stderr instead of stdout.
Fixes: https://github.com/asdf-vm/asdf/issues/308
> Print "No version set" message to stderr

- lib/commands/install.sh
- lib/commands/list.sh
- lib/commands/plugin-list-all.sh
- lib/commands/plugin-list.sh
- lib/commands/plugin-push.sh
- lib/commands/reshim.sh
- lib/utils.sh
- test/test_helpers.bash
- test/update_command.bats
Finally! The build is green again.
> Fix shellcheck warnings.

- completions/asdf.fish
It seems that fish recently changed how it handles white spaces in completions, so I was getting weird completions.
This should hopefully fix it.  
If anybody with on macOS using fish could check everything is working fine, it would be great.
Thank you.
> Fix fish shell completions

- test/test_helpers.bash
- test/utils.bats
@mwean I cherry picked some the changes from your PR that improved the test code. I set you as the author of the commit, so you should still get credit for your work on Github.
> Add another test for the ASDF_DATA_DIR functionality.

- asdf.sh
Fixes shims PATH stored under ASDF_DATA_DIR
> Fix user shims stored now in ASDF_DATA_DIR

- README.md
- lib/utils.sh
> Document asdf data dir

- lib/commands/plugin-list.sh
- test/plugin_current.bats
> Fix asdf current behaviour

- lib/utils.sh
- test/utils.bats
Updates resolve_symlink so it always returns absolute paths.
Fixes: #366
> Resolve symlinks fix

- README.md
Explain how shims work and how they're used to provide executables to
the environment. Also explain how to use scripts that are meant to be
sourced instead of executed.
Closes #215
> Document shims

- README.md
> Clarify README regarding `.tool-versions` lookup

- lib/commands/which.sh
- test/fixtures/dummy_plugin/bin/install
- test/which_command.bats
Updated which command. Now it searches for the binary file inside all bin-paths of all plugins in the current version
Fixes: #205 
If it needs any improvement, please let me know!
> Updated which command.

- test/utils.bats
> Add tests for versions set by environment variables

- bin/private/asdf-exec
- lib/commands/which.sh
- lib/utils.sh
- test/test_helpers.bash
- test/which_command.bats
Extract the `exec-path` logic into a function in utils.sh. Write test for the `exec-path` logic in the `which` command.
Fixes: #324
> Custom exec path tests

- docs/NEW_README.md
- docs/README.md
- docs/_404.md
- docs/_coverpage.md
- docs/_sidebar.md
- docs/core-configuration.md
- docs/core-manage-asdf-vm.md
- docs/core-manage-versions.md
- docs/homepage.md
- docs/index.html
- docs/thanks.md
This contains fixes and significant improvements to the documentation site.
* fixes some routing issues due to erroneous docsify config
* fixed links and layout of 404 pg
* improved the language on the landing page as per #438 
* propose a NEW_README.md tackling concerns with #438  and #422 
* use docsify specific md to emphasise some text
* add docsify-themeable plugin to improve loading experience and future proof for customisation
* improve use of `asdf-vm` over `asdf`
* I also added myself to the maintainer list :wink: 
Included in this PR is a file `docs/NEW_README.md` which is my proposed README for this repo. The intention was to have all documentation in a single place, the site, and simplify the readme bringing the focus to explaining the tool rather than instructing users on how …
> Significant documentation site improvements

- docs/contributing-doc-site.md
Add a wish-list for the docs-site to the Contributing part of the docs
> document documentation-wish-list in the docs

- docs/_coverpage.md
add "versions" to docs site subtitle as with #460
> add "versions" to docs subtitle

- README.md
Show users the URL in the README so they can become familiar with the domain we have.
We still need to get the URL in the repo header where near the repo topics
> show site url in readme

- lib/commands/update.sh
Hopefully will fix the update issues some have run into.
Fixes: #429
> Use asdf_dir instead of $ASDF_DIR

- completions/asdf.fish
Add `update` command to fish completions.
Fixes: #452
> Add update to Fish completions

- docs/core-manage-asdf-vm.md
note legacy version files in core setup guide
as suggested in https://github.com/asdf-vm/asdf/issues/499
> note legacy version files in core setup guide

- test/asdf_sh.bats
Write unit tests for code in asdf.sh.
Fixes: #286
> asdf.sh tests

- .travis.yml
- prepare-travis.sh
- test/asdf_fish.bats
Write unit tests for code in asdf.fish.
Fixes: #286
> Add tests for code in asdf.fish

- .travis.yml
We need to change the BATS we use to get around this issue:
https://github.com/sstephenson/bats/issues/171
> Switch to latest version of BATS

- lib/commands/install.sh
- test/install_command.bats
> Leonid shevtsov - install through plugins

- lib/commands/plugin-add.sh
We don't need all that noise 👂, it's getting kind of loud up in here.  😉
We will still see error messages if git-clone fails, but we don't have to see all the logs of everything getting cloned.
If there is anything else that is relevant to your pull request include that
information here.
> add quite flag to git clone

- CHANGELOG.md
- lib/commands/plugin-test.sh
> Make `asdf plugin test` determine plugin version with `asdf latest`

- .github/workflows/workflow.yml
- bin/asdf
- bin/private/asdf-exec
- completions/asdf.bash
- lib/asdf.sh
- lib/commands/command-current
- lib/commands/command-export-shell-version
- lib/commands/command-help
- lib/commands/command-install
- lib/commands/command-latest
- lib/commands/command-list
- lib/commands/command-list-all
- lib/commands/command-local
- lib/commands/command-plugin-list
- lib/commands/command-plugin-list-all
- lib/commands/command-plugin-test
- lib/commands/command-reshim
- lib/commands/command-uninstall
- lib/commands/command-update
- lib/commands/command-where
- lib/commands/reshim.sh
- lib/commands/version_commands.sh
- lib/utils.sh
- lint.sh
- prepare-travis.sh
- release/tag.sh
- test/fixtures/dummy_plugin/bin/install
- test/fixtures/dummy_plugin/bin/parse-legacy-file
- test/test_helpers.bash
> Enable github actions.

- docs/core-manage-asdf-vm.md
Adds a line of instruction for how to install with homebrew and pull in the latest changes from master.
Fixes: #598 
> Add instructions to use latest branch with Homebrew

- asdf.fish
- asdf.sh
- completions/asdf.bash
> Remove shebang lines of sourced scripts

- CHANGELOG.md
If there is anything else that is relevant to your pull request include that
information here.
> Fix small typo `git` -> `asdf`

- .github/workflows/workflow.yml
- test/update_command.bats
Git tags were not being fetched
> Fixes tests in master

- .github/workflows/workflow.yml
- lib/commands/command-help
- lib/commands/command-latest
- lib/commands/command-list-all
Also checkout specific tag of bats-core instead of using master.
> Prefer open source distros over closed source distros in build

- lib/utils.sh
- test/shim_exec.bats
Add back in support for path versions, and write additional unit tests for path versions.
Fixes: #559
> Fix Path Versions

- lib/commands/command-plugin-add.bash
- test/plugin_add_command.bats
Revert PR #688. Add unit tests
> Revert PR #688. Add unit tests

- docs/core-manage-asdf-vm.md
add dependencies for openSUSE and ArchLinux
> docs: asdf dependencies for openSUSE and ArchLinux

- bin/asdf
- docs/core-commands.md
- docs/core-manage-versions.md
- lib/utils.bash
- test/current_command.bats
- test/where_command.bats
Add the documentation and output for the shell command
Fixes: #715
> fix: asdf shell command docs & help output

- test/banned_commands.bats
Addresses @jthegedus comment on #754
> fix: ban the sort -V command

- lib/commands/command-plugin-update.bash
> Fix plugin-update --all when there are no plugins

- test/plugin_update_command.bats
> chore: basic tests for plugin-update command

- test/plugin_update_command.bats
Removes some unused code I introduced in #807. 
Fixes: #807
> Cleanup unused code in plugin update tests

- lib/utils.bash
- test/utils.bats
- test/version_commands.bats
> Fix resolution of relative symlinks

- SECURITY.md
- update latest supported version for security updates
- add @jthegedus contact details
> chore: jthegedus details. Update supported version

- CONTRIBUTING.md
Fix broken link in CONTRIBUTING.md
> fix broken link in CONTRIBUTING

- CONTRIBUTING.md
Add note about unsolicited formatting pull requests to CONTRIBUTING.md
Fixes: #847
> docs: note about unsolicited formatting pull requests

- README.md
- docs/_sidebar.md
- docs/plugins-create.md
- release/README.md
> docs: fix GitHub typo

- test/banned_commands.bats
> Add both the short and long versions of the --sort-versions flag to the banned commands

- README.md
> add missing word to readme

- asdf.fish
- bin/asdf
- bin/private/asdf-exec
- lib/asdf.fish
- lib/commands/command-global.bash
- lib/commands/command-list-all.bash
- lib/commands/command-local.bash
- lib/commands/command-plugin-test.bash
- lib/commands/command-reshim.bash
- lib/commands/command-uninstall.bash
- lib/utils.bash
- test/asdf_fish.bats
- test/banned_commands.bats
- test/version_commands.bats
> Add `source` to list of banned commands

- docs/core-manage-asdf.md
This replaces #704 who's source fork was orphaned (creating a new fork with a branch with the same name didn't resolve the issue).
I have addressed all feedback in #704 so recommend we close this out and accept new PRs with fixes should there be minor issues.
Fixes: #527
> docs: arch instructions w pacman

- release/tag.sh
Removes update to asdf version in README which we no longer use since doc site.
> chore: rm update of version in README as not used

- CHANGELOG.md
Clean up unused changelog heading.
> chore: rm unused changelog heading

- docs/manage/configuration.md
Describe `asdf_updates_disabled` in the docs as it is technically part of an API used by package managers (Homebrew, Pacman etc).
I think this is the best place for this type of documentation until we have more that warrants it's own section.
Fixes: #958
> docs: describe asdf_updates_disabled file purpose

- docs/index.md
Fix a small typo on the home page.
Fixes: None
N/A
> docs: fix typo in home page

- docs/guide/getting-started.md
- docs/manage/core.md
- docs/pt-br/guide/getting-started.md
- docs/pt-br/manage/core.md
Update docs with the new changes from Homebrew, now that https://github.com/Homebrew/homebrew-core/pull/81664 is merged.
> docs: add libexec to Homebrew path

- completions/_asdf
Small fix for asdf completions.
Fixes: #1060
> fix: completions for asdf plugin list

- docs/guide/getting-started.md
Correct commit message from PR #1085.
> fix: Correct typo on getting started page

- asdf.sh
> fix: newline after error msg for ASDF_DIR

- docs/plugins/create.md
> docs: Document the latest-stable callback plugin creation docs

- docs/guide/getting-started.md
Branch 0.8.1 no longer exists, leading to detached head upon checkout
> docs: update git/bash install docs to use 0.9.1

- docs/guide/getting-started.md
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
This pull request updates the install version from to the latest release from either `v0.9.0` or `v0.8.1`.
> docs: update version

- docs/pt-br/contribute/core.md
- docs/pt-br/contribute/documentation.md
- docs/pt-br/contribute/first-party-plugins.md
- docs/pt-br/contribute/github-actions.md
- docs/pt-br/guide/getting-started.md
- docs/pt-br/manage/commands.md
- docs/pt-br/manage/configuration.md
- docs/pt-br/manage/core.md
- docs/pt-br/manage/plugins.md
- docs/pt-br/plugins/create.md
docs: contributing to Portuguese translation in the documentation
> docs: updates portuguese translation in the documentation

- docs/pt-br/contribute/core.md
> fix: acronym change

- docs/zh-hans/guide/getting-started.md
- docs/zh-hans/manage/core.md
The zh-hans docs weren't properly updated in #1159
> docs: Update zh-hans instructions for elvish v0.18.0

- CHANGELOG.md
- docs/.vuepress/config.js
- docs/guide/getting-started.md
- docs/manage/plugins.md
- lib/commands/command-current.bash
- lib/utils.bash
- test/banned_commands.bats
- test/plugin_extension_command.bats
- test/utils.bats
- test/version_commands.bats
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/asdf/commit/fa3c8e928ce314d782471156ceb32f525871abe5#commitcomment-77688860
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/asdf/commit/680b0013893c9a725caf0a58c7e02db30b5a6c24
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
> chore: Fix spelling

- SECURITY.md
Update supported version list in security policy
> chore: update supported version list in sec policy

- completions/_asdf
- completions/asdf.bash
- completions/asdf.fish
> chore: Add `--all` completion to `asdf latest`

- README.md
Noticed the 'ballad' has gaps between the quoted verses, which looks like a mistake to me.
> fix: improve formatting of ballad

- .github/dependabot.yml
`monthly` is better here because we are likely to see many updates in the `npm` ecosystem, especially with the release candidates we're using for our docs site, and since we offer no APIs etc there is little risk delaying bugfixes in our static website
Trying to avoid Dependabot spam since it can't update more than one dependency per PR so we get ~5 at once
> ci: monthly dependabot npm schedule

- asdf.nu
- docs/guide/getting-started.md
Adds support for [nushell](https://www.nushell.sh/) with completions. 
Closes: #745
> feat: support nushell

- docs/plugins/create.md
A handful of typo fixes and wording cleanups in the plugin documentation.
Thanks for building this very useful tool.
> docs: fix typos in plugins-create page

- lib/functions/plugins.bash
- test/plugin_add_command.bats
I know this was marked as Good First Issue, but there shouldn't be any silent failures whatsoever. It's also been unresolved for two years
Closes #816
> fix: force lwrcase plugin name fix capitalization mismatch errs

- docs/more/community-projects.md
Addresses https://github.com/asdf-vm/asdf/pull/1390#discussion_r1057338940
> docs: clarify community projects are not asdf core team

- .tool-versions
- lib/commands/command-plugin-test.bash
- lib/utils.bash
Bump the tools in `.tool-versions` to the latest.
I am going on leave over the holiday period so may not be able to respond of complete this PR. Please feel free to resolve and merge in my absence.
> chore: bump dev deps

- .github/workflows/tests.yml
- asdf.nu
- docs/guide/getting-started.md
- test/asdf_nu.bats
Fix bug of using `first`  when hasn't a value for an expression
Fix support for `ASDF_DIR` env var
Add tests for nushell integration
Closes: #1382
> fix: Add test for nushell integration and fix some bugs

- docs/guide/getting-started.md
- docs/manage/core.md
- docs/pt-br/guide/getting-started.md
- docs/pt-br/manage/configuration.md
- docs/pt-br/manage/core.md
- docs/zh-hans/guide/getting-started.md
- docs/zh-hans/manage/core.md
ASDF is extremely popular and used by many people. I think it is a good idea to show best practices whenever shell code is written in. Mainly, the proper quoting of variables.
> docs: Properly quote variables in instructions

- .github/ISSUE_TEMPLATE/documentation
A template for users who wish to raise Documentation issues quickly.
I have run into wanting this enough to warrant creating it so I have a single button click and single text-box to copy-paste into 😅
> chore: github issue template for documentation

- .github/workflows/release.yml
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
A follow-up to https://github.com/asdf-vm/asdf/pull/1429
I didn't want to incorrectly translate anything, so I updated the structure of the translated pages and used English with the new text. Hopefully someone will PR an update to the translations.
> ci: release-please to bump versions in translated docs

- .github/workflows/lint.yml
- .github/workflows/tests.yml
Use https://github.com/rhysd/actionlint to lint our GitHub Actions workflow files
> ci: lint github actions with actionlint

- test/asdf_elvish.bats
- test/asdf_fish.bats
- test/asdf_nu.bats
- test/asdf_sh.bats
- test/current_command.bats
- test/get_asdf_config_value.bats
- test/help_command.bats
- test/info_command.bats
- test/install_command.bats
- test/list_command.bats
- test/plugin_add_command.bats
- test/plugin_list_all_command.bats
- test/shim_env_command.bats
- test/shim_exec.bats
- test/shim_versions_command.bats
- test/uninstall_command.bats
- test/update_command.bats
- test/utils.bats
- test/version_commands.bats
- test/which_command.bats
This PR is the **fourth** of a multi-part series that fixes various issues with the tests. For more detailed information, see the [first](https://github.com/asdf-vm/asdf/pull/1433) PR.
Partially addresses #1396
> chore: Fix ShellCheck errors in tests

- test/help_command.bats
- test/install_command.bats
- test/list_command.bats
- test/shim_exec.bats
- test/uninstall_command.bats
- test/utils.bats
Suggested in [this comment](https://github.com/asdf-vm/asdf/pull/1450#discussion_r1085363377)
> chore: Remove useless `echo`s in test/

- docs/manage/versions.md
Update output of `asdf current`. Also fix `asdf where` command example, as it will already output the install path of the current version installed if no specific version is given.
> docs: update format of example asdf commands

- test/help_command.bats
- test/info_command.bats
> test: assert info and help output

- .github/workflows/tests.yml
> ci: fix typo in workflow step name

- .github/workflows/tests.yml
- asdf.ps1
- docs/guide/getting-started.md
- docs/pt-br/guide/getting-started.md
- docs/zh-hans/guide/getting-started.md
- lib/commands/command-export-shell-version.bash
- test/asdf_pwsh.bats
Since _PowerShell Core_ is cross-platform, this adds support for it on _Linux only_. (Windows is still not officially supported)
Closes #576
- Tests (`test/asdf_pwsh.bats`)
- Documentation
- etc.
> feat: Support PowerShell Core

- test/banned_commands.bats
Adding this in preparation for https://github.com/asdf-vm/asdf/pull/667
> chore: only ban readlink -f

- lib/commands/command-plugin-remove.bash
> fix: improve readability of the non-set `nullglob` guard

- asdf.sh
> fix: Typo in POSIX entrypoint

- lib/functions/versions.bash
No longer write temporary files to home directory.
Fixes #1556
Fixes #1575
> fix: no longer write temporary files to home directory

- asdf.fish
> fix: Make asdf.fish compatible with Fish 3.1.2

- docs/pt-br/index.md
> Fix wrong spelling of pt-br word vários

- bin/asdf
Partially addresses #160. Draft until `v0.13.0` is released.
> fix!: Enable `pipefail`

- test/asdf_fish.bats
This adds a flag to improve test isolation.
> test(fish): Improve test isolation

- .github/workflows/release-build.yml
> chore(golang-rewrite): disable dev releases and builds

- internal/cli/cli.go
- internal/cli/set/set.go
- internal/cli/set/set_test.go
- internal/help/help.txt
- internal/toolversions/toolversions.go
- internal/toolversions/toolversions_test.go
* Create `toolversions.updateContentWithToolVersions` and `toolversions.WriteToolVersionsToFile` functions
* Add `asdf set` command to help text
* Implement `asdf set` command
* Add support for latest version to `asdf set` command
> feat(golang-rewrite): implement `asdf set` command

- docs/guide/upgrading-from-v0-15-to-v0-16.md
Updates docs with changes made in #1829
> chore(docs): update breaking changes documentation

- .github/workflows/lint.yml
- scripts/install_dependencies.bash
Got tired of having to change the fish version all the time due to broken build, so I updated the script to install the latest available version.
> chore: update dependency versions

- .github/workflows/release.yml
- .release-please-manifest.json
* Get `release-please-action` working again
* Correct `.release-please-manifest.json` syntax
> chore(golang-rewrite): fix release.yml

- internal/cli/cli.go
- test/where_command.bats
Fixes https://github.com/asdf-vm/asdf/issues/1862
> fix: replace reference to removed subcommands

- docs/ja-jp/manage/commands.md
- docs/ko-kr/manage/commands.md
- docs/manage/commands.md
- docs/pt-br/manage/commands.md
- docs/zh-hans/manage/commands.md
Fixes: https://github.com/asdf-vm/asdf/issues/1888, https://github.com/asdf-vm/asdf/pull/1885
> docs: update docs to show new help output

- internal/cli/set/set.go
- internal/help/help.txt
Also ensure asdf set command prints all errors
Fixes: https://github.com/asdf-vm/asdf/issues/1918
> fix: correct help for asdf set command

- internal/cli/cli.go
- internal/completions/asdf.bash
- internal/completions/asdf.fish
- internal/completions/asdf.nushell
- internal/completions/asdf.zsh
Adds the missing version command.
Fixes: #1915
> fix: add missing version command

- docs/manage/versions.md
Fix broken anchor link in docs
Fixes: n/a
n/a
> docs: fix reference to renamed section header

- docs/guide/upgrading-to-v0-16.md
Fixes https://github.com/asdf-vm/asdf/issues/1902
> docs: add missing asdf reshim step to migration guide

- internal/execenv/execenv.go
- internal/execenv/execenv_test.go
Fixes https://github.com/asdf-vm/asdf/pull/1879
Relates to https://github.com/asdf-vm/asdf/issues/1876
> fix: support environment variables with equals sign and newlines in value

- internal/git/git.go
- internal/git/git_test.go
- internal/repotest/repotest.go
- internal/versions/versions.go
some work on #1998 which is related to #1882
Just to fix current pr check issues, i've also tried to finish some of the code, i have checked it in local for install/update a plugin on a private repository and initially looks like working ok.
I'lll be using it on my daily-basis and let you know if i find something strange on that code.
> refactor: native-git-client fix tests and some minor changes

- internal/versions/versions.go
- internal/versions/versions_test.go
This PR builds on https://github.com/asdf-vm/asdf/pull/2030
And fixes https://github.com/augustobmoura/asdf-protonge/issues/4
> fix: remove filtering from latest-stable call

- docs/plugins/create.md
Fixes link from https://asdf-vm.com/plugins/create.html#bin-install to https://asdf-vm.com/plugins/create.html#bin-list-bin-paths
> docs: Fix link to bin/list-bin-paths

- internal/git/git.go
- internal/git/git_test.go
- internal/plugins/plugins_test.go
- internal/repotest/repotest.go
* update internal/git package to use native Git client not go-git package                                               
* improve git package error messages
> feat: switch back to native git client

- docs/more/faq.md
Related to https://github.com/asdf-vm/asdf/issues/1736
> docs: add faq item on use of latest in .tool-versions files

- .tool-versions
- cmd/asdf/main_test.go
- internal/cli/cli.go
- test/shim_exec.bats
Fixes https://github.com/asdf-vm/asdf/issues/2108
> fix: print all error output to stderr when shim can't be resolved

- docs/more/faq.md
> docs: document unexpected shims on faq page

- .gitignore
- docs/guide/upgrading-to-v0-16.md
Fixes: https://github.com/asdf-vm/asdf/issues/1880
> docs: document cleanup of ASDF_DATA_DIR in upgrade guide

- docs/guide/upgrading-to-v0-16.md
Fixes https://github.com/asdf-vm/asdf/issues/2069
> docs: upgrade upgrade guide to reference all available install methods

- docs/ko-kr/manage/configuration.md
- docs/manage/configuration.md
Fixes: https://github.com/asdf-vm/asdf/issues/1763
> docs: correct link to ASDF_CONFIG_FILE environment variable

- docs/guide/upgrading-to-v0-16.md
Fixes https://github.com/asdf-vm/asdf/issues/2121
I tested this locally and works regardless of the directory it is run in.
> docs: correct dangerous cleanup command in upgrade guide
